////////////////////////////////////////////////////
 This file is made from Stub.h to make reading easier
 ////////////////////////////////////////////////////
/* Stub.h
   Generated by gSOAP 2.8.8 from schem.h
*/
class SOAP_CMAC _icd1__GetTime
{
};

class SOAP_CMAC _icd1__GetTimeResponse
{
	std::string *GetTimeResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__LoginDevice
{
	int idd;	/* required element of type xsd:int */
	std::string *name;	/* optional element of type xsd:string */
	std::string *devInfo;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__LoginDeviceResponse
{
	int LoginDeviceResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	std::string *message;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__SendData
{
	std::string *data;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__SendDataResponse
{
	int SendDataResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	std::string *message;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__LogoutDevice
{
};

class SOAP_CMAC _icd1__LogoutDeviceResponse
{
	int LogoutDeviceResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	std::string *message;	/* optional element of type xsd:string */
};

/* Operation wrapper: */
struct __icd2__GetTime
{
	_icd1__GetTime *icd1__GetTime;	/* optional element of type icd1:GetTime */
};

/* Operation wrapper: */
struct __icd2__LoginDevice
{
	_icd1__LoginDevice *icd1__LoginDevice;	/* optional element of type icd1:LoginDevice */
};

/* Operation wrapper: */
struct __icd2__SendData
{
	_icd1__SendData *icd1__SendData;	/* optional element of type icd1:SendData */
};

/* Operation wrapper: */
struct __icd2__LogoutDevice
{
	_icd1__LogoutDevice *icd1__LogoutDevice;	/* optional element of type icd1:LogoutDevice */
};

/* Operation wrapper: */
struct __icd3__GetTime
{
	_icd1__GetTime *icd1__GetTime;	/* optional element of type icd1:GetTime */
};

/* Operation wrapper: */
struct __icd3__LoginDevice
{
	_icd1__LoginDevice *icd1__LoginDevice;	/* optional element of type icd1:LoginDevice */
};

/* Operation wrapper: */
struct __icd3__SendData
{
	_icd1__SendData *icd1__SendData;	/* optional element of type icd1:SendData */
};

/* Operation wrapper: */
struct __icd3__LogoutDevice
{
	_icd1__LogoutDevice *icd1__LogoutDevice;	/* optional element of type icd1:LogoutDevice */
};

/* SOAP Header: */
struct SOAP_ENV__Header
{
private:
	char dummy;	/* dummy member to enable compilation */
};

/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};

/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};

/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};

/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};

typedef char *_QName;
typedef char *_XML;
/* End of Stub.h */
