////////////////////////////////////////////////////
 This file is made from Stub.h to make reading easier
 ////////////////////////////////////////////////////
/* Stub.h
   Generated by gSOAP 2.8.8 from schem.h
*/
class SOAP_CMAC icd1__UpdatePack
{
	std::string *Link;	/* optional element of type xsd:string */
	std::string *md5;	/* optional element of type xsd:string */
	int FileSize;	/* required element of type xsd:int */
	std::string *UpdateForce;	/* optional element of type xsd:string */
	std::string *NewVersion;	/* optional element of type xsd:string */
};

class SOAP_CMAC icd1__GetMacIddPack
{
	int Idd;	/* required element of type xsd:int */
	std::string *mac;	/* optional element of type xsd:string */
	std::string *message;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__GetTime
{
};

class SOAP_CMAC _icd1__GetTimeResponse
{
	std::string *GetTimeResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__LoginDevice
{
	int idd;	/* required element of type xsd:int */
	std::string *mac;	/* optional element of type xsd:string */
	std::string *deviceIds;	/* optional element of type xsd:string */
	std::string *devInfo;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__LoginDeviceResponse
{
	int LoginDeviceResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	std::string *message;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__SendData
{
	std::string *data;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__SendDataResponse
{
	int SendDataResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	std::string *message;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__SendData3
{
	std::string *data;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__SendData3Response
{
	int SendData3Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	std::string *message;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__LogoutDevice
{
};

class SOAP_CMAC _icd1__LogoutDeviceResponse
{
	int LogoutDeviceResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	std::string *message;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__TestSession
{
};

class SOAP_CMAC _icd1__TestSessionResponse
{
	int TestSessionResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};

class SOAP_CMAC _icd1__GetDeviceUpdateInfo
{
	std::string *softVersion;	/* optional element of type xsd:string */
};

class SOAP_CMAC _icd1__GetDeviceUpdateInfoResponse
{
	int GetDeviceUpdateInfoResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	icd1__UpdatePack *response;	/* optional element of type icd1:UpdatePack */
};

class SOAP_CMAC _icd1__GetMacIdd
{
};

class SOAP_CMAC _icd1__GetMacIddResponse
{
	int GetMacIddResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	icd1__GetMacIddPack *response;	/* optional element of type icd1:GetMacIddPack */
};

/* Operation wrapper: */
struct __icd2__GetTime
{
	_icd1__GetTime *icd1__GetTime;	/* optional element of type icd1:GetTime */
};

/* Operation wrapper: */
struct __icd2__LoginDevice
{
	_icd1__LoginDevice *icd1__LoginDevice;	/* optional element of type icd1:LoginDevice */
};

/* Operation wrapper: */
struct __icd2__SendData
{
	_icd1__SendData *icd1__SendData;	/* optional element of type icd1:SendData */
};

/* Operation wrapper: */
struct __icd2__SendData3
{
	_icd1__SendData3 *icd1__SendData3;	/* optional element of type icd1:SendData3 */
};

/* Operation wrapper: */
struct __icd2__LogoutDevice
{
	_icd1__LogoutDevice *icd1__LogoutDevice;	/* optional element of type icd1:LogoutDevice */
};

/* Operation wrapper: */
struct __icd2__TestSession
{
	_icd1__TestSession *icd1__TestSession;	/* optional element of type icd1:TestSession */
};

/* Operation wrapper: */
struct __icd2__GetDeviceUpdateInfo
{
	_icd1__GetDeviceUpdateInfo *icd1__GetDeviceUpdateInfo;	/* optional element of type icd1:GetDeviceUpdateInfo */
};

/* Operation wrapper: */
struct __icd2__GetMacIdd
{
	_icd1__GetMacIdd *icd1__GetMacIdd;	/* optional element of type icd1:GetMacIdd */
};

/* Operation wrapper: */
struct __icd3__GetTime
{
	_icd1__GetTime *icd1__GetTime;	/* optional element of type icd1:GetTime */
};

/* Operation wrapper: */
struct __icd3__LoginDevice
{
	_icd1__LoginDevice *icd1__LoginDevice;	/* optional element of type icd1:LoginDevice */
};

/* Operation wrapper: */
struct __icd3__SendData
{
	_icd1__SendData *icd1__SendData;	/* optional element of type icd1:SendData */
};

/* Operation wrapper: */
struct __icd3__SendData3
{
	_icd1__SendData3 *icd1__SendData3;	/* optional element of type icd1:SendData3 */
};

/* Operation wrapper: */
struct __icd3__LogoutDevice
{
	_icd1__LogoutDevice *icd1__LogoutDevice;	/* optional element of type icd1:LogoutDevice */
};

/* Operation wrapper: */
struct __icd3__TestSession
{
	_icd1__TestSession *icd1__TestSession;	/* optional element of type icd1:TestSession */
};

/* Operation wrapper: */
struct __icd3__GetDeviceUpdateInfo
{
	_icd1__GetDeviceUpdateInfo *icd1__GetDeviceUpdateInfo;	/* optional element of type icd1:GetDeviceUpdateInfo */
};

/* Operation wrapper: */
struct __icd3__GetMacIdd
{
	_icd1__GetMacIdd *icd1__GetMacIdd;	/* optional element of type icd1:GetMacIdd */
};

/* SOAP Header: */
struct SOAP_ENV__Header
{
private:
	char dummy;	/* dummy member to enable compilation */
};

/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};

/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};

/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};

/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};

typedef char *_QName;
typedef char *_XML;
/* End of Stub.h */
