/* H.h
   Generated by gSOAP 2.8.8 from schem.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef H_H
#define H_H
#include "Stub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 _instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 _fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 _container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "string", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__GetMacIddResponse
#define SOAP_TYPE__icd1__GetMacIddResponse (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__GetMacIddResponse(struct soap*, const char*, int, const _icd1__GetMacIddResponse *, const char*);
SOAP_FMAC3 _icd1__GetMacIddResponse * SOAP_FMAC4 soap_in__icd1__GetMacIddResponse(struct soap*, const char*, _icd1__GetMacIddResponse *, const char*);

#ifndef soap_write__icd1__GetMacIddResponse
#define soap_write__icd1__GetMacIddResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:GetMacIddResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__GetMacIddResponse
#define soap_read__icd1__GetMacIddResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__GetMacIddResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__GetMacIddResponse * SOAP_FMAC4 soap_get__icd1__GetMacIddResponse(struct soap*, _icd1__GetMacIddResponse *, const char*, const char*);

#define soap_new__icd1__GetMacIddResponse(soap, n) soap_instantiate__icd1__GetMacIddResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__GetMacIddResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__GetMacIddResponse * SOAP_FMAC2 soap_instantiate__icd1__GetMacIddResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__GetMacIddResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__GetMacIdd
#define SOAP_TYPE__icd1__GetMacIdd (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__GetMacIdd(struct soap*, const char*, int, const _icd1__GetMacIdd *, const char*);
SOAP_FMAC3 _icd1__GetMacIdd * SOAP_FMAC4 soap_in__icd1__GetMacIdd(struct soap*, const char*, _icd1__GetMacIdd *, const char*);

#ifndef soap_write__icd1__GetMacIdd
#define soap_write__icd1__GetMacIdd(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:GetMacIdd", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__GetMacIdd
#define soap_read__icd1__GetMacIdd(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__GetMacIdd(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__GetMacIdd * SOAP_FMAC4 soap_get__icd1__GetMacIdd(struct soap*, _icd1__GetMacIdd *, const char*, const char*);

#define soap_new__icd1__GetMacIdd(soap, n) soap_instantiate__icd1__GetMacIdd(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__GetMacIdd(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__GetMacIdd * SOAP_FMAC2 soap_instantiate__icd1__GetMacIdd(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__GetMacIdd(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__GetDeviceUpdateInfoResponse
#define SOAP_TYPE__icd1__GetDeviceUpdateInfoResponse (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__GetDeviceUpdateInfoResponse(struct soap*, const char*, int, const _icd1__GetDeviceUpdateInfoResponse *, const char*);
SOAP_FMAC3 _icd1__GetDeviceUpdateInfoResponse * SOAP_FMAC4 soap_in__icd1__GetDeviceUpdateInfoResponse(struct soap*, const char*, _icd1__GetDeviceUpdateInfoResponse *, const char*);

#ifndef soap_write__icd1__GetDeviceUpdateInfoResponse
#define soap_write__icd1__GetDeviceUpdateInfoResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:GetDeviceUpdateInfoResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__GetDeviceUpdateInfoResponse
#define soap_read__icd1__GetDeviceUpdateInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__GetDeviceUpdateInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__GetDeviceUpdateInfoResponse * SOAP_FMAC4 soap_get__icd1__GetDeviceUpdateInfoResponse(struct soap*, _icd1__GetDeviceUpdateInfoResponse *, const char*, const char*);

#define soap_new__icd1__GetDeviceUpdateInfoResponse(soap, n) soap_instantiate__icd1__GetDeviceUpdateInfoResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__GetDeviceUpdateInfoResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__GetDeviceUpdateInfoResponse * SOAP_FMAC2 soap_instantiate__icd1__GetDeviceUpdateInfoResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__GetDeviceUpdateInfoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__GetDeviceUpdateInfo
#define SOAP_TYPE__icd1__GetDeviceUpdateInfo (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__GetDeviceUpdateInfo(struct soap*, const char*, int, const _icd1__GetDeviceUpdateInfo *, const char*);
SOAP_FMAC3 _icd1__GetDeviceUpdateInfo * SOAP_FMAC4 soap_in__icd1__GetDeviceUpdateInfo(struct soap*, const char*, _icd1__GetDeviceUpdateInfo *, const char*);

#ifndef soap_write__icd1__GetDeviceUpdateInfo
#define soap_write__icd1__GetDeviceUpdateInfo(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:GetDeviceUpdateInfo", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__GetDeviceUpdateInfo
#define soap_read__icd1__GetDeviceUpdateInfo(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__GetDeviceUpdateInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__GetDeviceUpdateInfo * SOAP_FMAC4 soap_get__icd1__GetDeviceUpdateInfo(struct soap*, _icd1__GetDeviceUpdateInfo *, const char*, const char*);

#define soap_new__icd1__GetDeviceUpdateInfo(soap, n) soap_instantiate__icd1__GetDeviceUpdateInfo(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__GetDeviceUpdateInfo(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__GetDeviceUpdateInfo * SOAP_FMAC2 soap_instantiate__icd1__GetDeviceUpdateInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__GetDeviceUpdateInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__TestSessionResponse
#define SOAP_TYPE__icd1__TestSessionResponse (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__TestSessionResponse(struct soap*, const char*, int, const _icd1__TestSessionResponse *, const char*);
SOAP_FMAC3 _icd1__TestSessionResponse * SOAP_FMAC4 soap_in__icd1__TestSessionResponse(struct soap*, const char*, _icd1__TestSessionResponse *, const char*);

#ifndef soap_write__icd1__TestSessionResponse
#define soap_write__icd1__TestSessionResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:TestSessionResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__TestSessionResponse
#define soap_read__icd1__TestSessionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__TestSessionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__TestSessionResponse * SOAP_FMAC4 soap_get__icd1__TestSessionResponse(struct soap*, _icd1__TestSessionResponse *, const char*, const char*);

#define soap_new__icd1__TestSessionResponse(soap, n) soap_instantiate__icd1__TestSessionResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__TestSessionResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__TestSessionResponse * SOAP_FMAC2 soap_instantiate__icd1__TestSessionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__TestSessionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__TestSession
#define SOAP_TYPE__icd1__TestSession (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__TestSession(struct soap*, const char*, int, const _icd1__TestSession *, const char*);
SOAP_FMAC3 _icd1__TestSession * SOAP_FMAC4 soap_in__icd1__TestSession(struct soap*, const char*, _icd1__TestSession *, const char*);

#ifndef soap_write__icd1__TestSession
#define soap_write__icd1__TestSession(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:TestSession", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__TestSession
#define soap_read__icd1__TestSession(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__TestSession(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__TestSession * SOAP_FMAC4 soap_get__icd1__TestSession(struct soap*, _icd1__TestSession *, const char*, const char*);

#define soap_new__icd1__TestSession(soap, n) soap_instantiate__icd1__TestSession(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__TestSession(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__TestSession * SOAP_FMAC2 soap_instantiate__icd1__TestSession(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__TestSession(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__LogoutDeviceResponse
#define SOAP_TYPE__icd1__LogoutDeviceResponse (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__LogoutDeviceResponse(struct soap*, const char*, int, const _icd1__LogoutDeviceResponse *, const char*);
SOAP_FMAC3 _icd1__LogoutDeviceResponse * SOAP_FMAC4 soap_in__icd1__LogoutDeviceResponse(struct soap*, const char*, _icd1__LogoutDeviceResponse *, const char*);

#ifndef soap_write__icd1__LogoutDeviceResponse
#define soap_write__icd1__LogoutDeviceResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:LogoutDeviceResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__LogoutDeviceResponse
#define soap_read__icd1__LogoutDeviceResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__LogoutDeviceResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__LogoutDeviceResponse * SOAP_FMAC4 soap_get__icd1__LogoutDeviceResponse(struct soap*, _icd1__LogoutDeviceResponse *, const char*, const char*);

#define soap_new__icd1__LogoutDeviceResponse(soap, n) soap_instantiate__icd1__LogoutDeviceResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__LogoutDeviceResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__LogoutDeviceResponse * SOAP_FMAC2 soap_instantiate__icd1__LogoutDeviceResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__LogoutDeviceResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__LogoutDevice
#define SOAP_TYPE__icd1__LogoutDevice (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__LogoutDevice(struct soap*, const char*, int, const _icd1__LogoutDevice *, const char*);
SOAP_FMAC3 _icd1__LogoutDevice * SOAP_FMAC4 soap_in__icd1__LogoutDevice(struct soap*, const char*, _icd1__LogoutDevice *, const char*);

#ifndef soap_write__icd1__LogoutDevice
#define soap_write__icd1__LogoutDevice(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:LogoutDevice", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__LogoutDevice
#define soap_read__icd1__LogoutDevice(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__LogoutDevice(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__LogoutDevice * SOAP_FMAC4 soap_get__icd1__LogoutDevice(struct soap*, _icd1__LogoutDevice *, const char*, const char*);

#define soap_new__icd1__LogoutDevice(soap, n) soap_instantiate__icd1__LogoutDevice(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__LogoutDevice(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__LogoutDevice * SOAP_FMAC2 soap_instantiate__icd1__LogoutDevice(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__LogoutDevice(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__SendData3Response
#define SOAP_TYPE__icd1__SendData3Response (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__SendData3Response(struct soap*, const char*, int, const _icd1__SendData3Response *, const char*);
SOAP_FMAC3 _icd1__SendData3Response * SOAP_FMAC4 soap_in__icd1__SendData3Response(struct soap*, const char*, _icd1__SendData3Response *, const char*);

#ifndef soap_write__icd1__SendData3Response
#define soap_write__icd1__SendData3Response(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:SendData3Response", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__SendData3Response
#define soap_read__icd1__SendData3Response(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__SendData3Response(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__SendData3Response * SOAP_FMAC4 soap_get__icd1__SendData3Response(struct soap*, _icd1__SendData3Response *, const char*, const char*);

#define soap_new__icd1__SendData3Response(soap, n) soap_instantiate__icd1__SendData3Response(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__SendData3Response(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__SendData3Response * SOAP_FMAC2 soap_instantiate__icd1__SendData3Response(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__SendData3Response(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__SendData3
#define SOAP_TYPE__icd1__SendData3 (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__SendData3(struct soap*, const char*, int, const _icd1__SendData3 *, const char*);
SOAP_FMAC3 _icd1__SendData3 * SOAP_FMAC4 soap_in__icd1__SendData3(struct soap*, const char*, _icd1__SendData3 *, const char*);

#ifndef soap_write__icd1__SendData3
#define soap_write__icd1__SendData3(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:SendData3", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__SendData3
#define soap_read__icd1__SendData3(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__SendData3(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__SendData3 * SOAP_FMAC4 soap_get__icd1__SendData3(struct soap*, _icd1__SendData3 *, const char*, const char*);

#define soap_new__icd1__SendData3(soap, n) soap_instantiate__icd1__SendData3(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__SendData3(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__SendData3 * SOAP_FMAC2 soap_instantiate__icd1__SendData3(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__SendData3(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__SendDataResponse
#define SOAP_TYPE__icd1__SendDataResponse (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__SendDataResponse(struct soap*, const char*, int, const _icd1__SendDataResponse *, const char*);
SOAP_FMAC3 _icd1__SendDataResponse * SOAP_FMAC4 soap_in__icd1__SendDataResponse(struct soap*, const char*, _icd1__SendDataResponse *, const char*);

#ifndef soap_write__icd1__SendDataResponse
#define soap_write__icd1__SendDataResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:SendDataResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__SendDataResponse
#define soap_read__icd1__SendDataResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__SendDataResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__SendDataResponse * SOAP_FMAC4 soap_get__icd1__SendDataResponse(struct soap*, _icd1__SendDataResponse *, const char*, const char*);

#define soap_new__icd1__SendDataResponse(soap, n) soap_instantiate__icd1__SendDataResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__SendDataResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__SendDataResponse * SOAP_FMAC2 soap_instantiate__icd1__SendDataResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__SendDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__SendData
#define SOAP_TYPE__icd1__SendData (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__SendData(struct soap*, const char*, int, const _icd1__SendData *, const char*);
SOAP_FMAC3 _icd1__SendData * SOAP_FMAC4 soap_in__icd1__SendData(struct soap*, const char*, _icd1__SendData *, const char*);

#ifndef soap_write__icd1__SendData
#define soap_write__icd1__SendData(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:SendData", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__SendData
#define soap_read__icd1__SendData(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__SendData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__SendData * SOAP_FMAC4 soap_get__icd1__SendData(struct soap*, _icd1__SendData *, const char*, const char*);

#define soap_new__icd1__SendData(soap, n) soap_instantiate__icd1__SendData(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__SendData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__SendData * SOAP_FMAC2 soap_instantiate__icd1__SendData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__SendData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__LoginDeviceResponse
#define SOAP_TYPE__icd1__LoginDeviceResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__LoginDeviceResponse(struct soap*, const char*, int, const _icd1__LoginDeviceResponse *, const char*);
SOAP_FMAC3 _icd1__LoginDeviceResponse * SOAP_FMAC4 soap_in__icd1__LoginDeviceResponse(struct soap*, const char*, _icd1__LoginDeviceResponse *, const char*);

#ifndef soap_write__icd1__LoginDeviceResponse
#define soap_write__icd1__LoginDeviceResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:LoginDeviceResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__LoginDeviceResponse
#define soap_read__icd1__LoginDeviceResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__LoginDeviceResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__LoginDeviceResponse * SOAP_FMAC4 soap_get__icd1__LoginDeviceResponse(struct soap*, _icd1__LoginDeviceResponse *, const char*, const char*);

#define soap_new__icd1__LoginDeviceResponse(soap, n) soap_instantiate__icd1__LoginDeviceResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__LoginDeviceResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__LoginDeviceResponse * SOAP_FMAC2 soap_instantiate__icd1__LoginDeviceResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__LoginDeviceResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__LoginDevice
#define SOAP_TYPE__icd1__LoginDevice (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__LoginDevice(struct soap*, const char*, int, const _icd1__LoginDevice *, const char*);
SOAP_FMAC3 _icd1__LoginDevice * SOAP_FMAC4 soap_in__icd1__LoginDevice(struct soap*, const char*, _icd1__LoginDevice *, const char*);

#ifndef soap_write__icd1__LoginDevice
#define soap_write__icd1__LoginDevice(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:LoginDevice", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__LoginDevice
#define soap_read__icd1__LoginDevice(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__LoginDevice(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__LoginDevice * SOAP_FMAC4 soap_get__icd1__LoginDevice(struct soap*, _icd1__LoginDevice *, const char*, const char*);

#define soap_new__icd1__LoginDevice(soap, n) soap_instantiate__icd1__LoginDevice(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__LoginDevice(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__LoginDevice * SOAP_FMAC2 soap_instantiate__icd1__LoginDevice(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__LoginDevice(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__GetTimeResponse
#define SOAP_TYPE__icd1__GetTimeResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__GetTimeResponse(struct soap*, const char*, int, const _icd1__GetTimeResponse *, const char*);
SOAP_FMAC3 _icd1__GetTimeResponse * SOAP_FMAC4 soap_in__icd1__GetTimeResponse(struct soap*, const char*, _icd1__GetTimeResponse *, const char*);

#ifndef soap_write__icd1__GetTimeResponse
#define soap_write__icd1__GetTimeResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:GetTimeResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__GetTimeResponse
#define soap_read__icd1__GetTimeResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__GetTimeResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__GetTimeResponse * SOAP_FMAC4 soap_get__icd1__GetTimeResponse(struct soap*, _icd1__GetTimeResponse *, const char*, const char*);

#define soap_new__icd1__GetTimeResponse(soap, n) soap_instantiate__icd1__GetTimeResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__GetTimeResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__GetTimeResponse * SOAP_FMAC2 soap_instantiate__icd1__GetTimeResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__GetTimeResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__icd1__GetTime
#define SOAP_TYPE__icd1__GetTime (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__icd1__GetTime(struct soap*, const char*, int, const _icd1__GetTime *, const char*);
SOAP_FMAC3 _icd1__GetTime * SOAP_FMAC4 soap_in__icd1__GetTime(struct soap*, const char*, _icd1__GetTime *, const char*);

#ifndef soap_write__icd1__GetTime
#define soap_write__icd1__GetTime(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:GetTime", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__icd1__GetTime
#define soap_read__icd1__GetTime(soap, data) ( soap_begin_recv(soap) || !soap_get__icd1__GetTime(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__GetTime * SOAP_FMAC4 soap_get__icd1__GetTime(struct soap*, _icd1__GetTime *, const char*, const char*);

#define soap_new__icd1__GetTime(soap, n) soap_instantiate__icd1__GetTime(soap, n, NULL, NULL, NULL)


#define soap_delete__icd1__GetTime(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _icd1__GetTime * SOAP_FMAC2 soap_instantiate__icd1__GetTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__icd1__GetTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_icd1__GetMacIddPack
#define SOAP_TYPE_icd1__GetMacIddPack (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_icd1__GetMacIddPack(struct soap*, const char*, int, const icd1__GetMacIddPack *, const char*);
SOAP_FMAC3 icd1__GetMacIddPack * SOAP_FMAC4 soap_in_icd1__GetMacIddPack(struct soap*, const char*, icd1__GetMacIddPack *, const char*);

#ifndef soap_write_icd1__GetMacIddPack
#define soap_write_icd1__GetMacIddPack(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:GetMacIddPack", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_icd1__GetMacIddPack
#define soap_read_icd1__GetMacIddPack(soap, data) ( soap_begin_recv(soap) || !soap_get_icd1__GetMacIddPack(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 icd1__GetMacIddPack * SOAP_FMAC4 soap_get_icd1__GetMacIddPack(struct soap*, icd1__GetMacIddPack *, const char*, const char*);

#define soap_new_icd1__GetMacIddPack(soap, n) soap_instantiate_icd1__GetMacIddPack(soap, n, NULL, NULL, NULL)


#define soap_delete_icd1__GetMacIddPack(soap, p) soap_delete(soap, p)

SOAP_FMAC1 icd1__GetMacIddPack * SOAP_FMAC2 soap_instantiate_icd1__GetMacIddPack(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_icd1__GetMacIddPack(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_icd1__UpdatePack
#define SOAP_TYPE_icd1__UpdatePack (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_icd1__UpdatePack(struct soap*, const char*, int, const icd1__UpdatePack *, const char*);
SOAP_FMAC3 icd1__UpdatePack * SOAP_FMAC4 soap_in_icd1__UpdatePack(struct soap*, const char*, icd1__UpdatePack *, const char*);

#ifndef soap_write_icd1__UpdatePack
#define soap_write_icd1__UpdatePack(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "icd1:UpdatePack", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_icd1__UpdatePack
#define soap_read_icd1__UpdatePack(soap, data) ( soap_begin_recv(soap) || !soap_get_icd1__UpdatePack(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 icd1__UpdatePack * SOAP_FMAC4 soap_get_icd1__UpdatePack(struct soap*, icd1__UpdatePack *, const char*, const char*);

#define soap_new_icd1__UpdatePack(soap, n) soap_instantiate_icd1__UpdatePack(soap, n, NULL, NULL, NULL)


#define soap_delete_icd1__UpdatePack(soap, p) soap_delete(soap, p)

SOAP_FMAC1 icd1__UpdatePack * SOAP_FMAC2 soap_instantiate_icd1__UpdatePack(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_icd1__UpdatePack(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (86)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (85)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___icd3__GetMacIdd
#define SOAP_TYPE___icd3__GetMacIdd (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd3__GetMacIdd(struct soap*, struct __icd3__GetMacIdd *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd3__GetMacIdd(struct soap*, const struct __icd3__GetMacIdd *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd3__GetMacIdd(struct soap*, const char*, int, const struct __icd3__GetMacIdd *, const char*);
SOAP_FMAC3 struct __icd3__GetMacIdd * SOAP_FMAC4 soap_in___icd3__GetMacIdd(struct soap*, const char*, struct __icd3__GetMacIdd *, const char*);

#ifndef soap_write___icd3__GetMacIdd
#define soap_write___icd3__GetMacIdd(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd3__GetMacIdd(soap, data), 0) || soap_put___icd3__GetMacIdd(soap, data, "-icd3:GetMacIdd", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd3__GetMacIdd(struct soap*, const struct __icd3__GetMacIdd *, const char*, const char*);

#ifndef soap_read___icd3__GetMacIdd
#define soap_read___icd3__GetMacIdd(soap, data) ( soap_begin_recv(soap) || !soap_get___icd3__GetMacIdd(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd3__GetMacIdd * SOAP_FMAC4 soap_get___icd3__GetMacIdd(struct soap*, struct __icd3__GetMacIdd *, const char*, const char*);

#define soap_new___icd3__GetMacIdd(soap, n) soap_instantiate___icd3__GetMacIdd(soap, n, NULL, NULL, NULL)


#define soap_delete___icd3__GetMacIdd(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd3__GetMacIdd * SOAP_FMAC2 soap_instantiate___icd3__GetMacIdd(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd3__GetMacIdd(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd3__GetDeviceUpdateInfo
#define SOAP_TYPE___icd3__GetDeviceUpdateInfo (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd3__GetDeviceUpdateInfo(struct soap*, struct __icd3__GetDeviceUpdateInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd3__GetDeviceUpdateInfo(struct soap*, const struct __icd3__GetDeviceUpdateInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd3__GetDeviceUpdateInfo(struct soap*, const char*, int, const struct __icd3__GetDeviceUpdateInfo *, const char*);
SOAP_FMAC3 struct __icd3__GetDeviceUpdateInfo * SOAP_FMAC4 soap_in___icd3__GetDeviceUpdateInfo(struct soap*, const char*, struct __icd3__GetDeviceUpdateInfo *, const char*);

#ifndef soap_write___icd3__GetDeviceUpdateInfo
#define soap_write___icd3__GetDeviceUpdateInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd3__GetDeviceUpdateInfo(soap, data), 0) || soap_put___icd3__GetDeviceUpdateInfo(soap, data, "-icd3:GetDeviceUpdateInfo", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd3__GetDeviceUpdateInfo(struct soap*, const struct __icd3__GetDeviceUpdateInfo *, const char*, const char*);

#ifndef soap_read___icd3__GetDeviceUpdateInfo
#define soap_read___icd3__GetDeviceUpdateInfo(soap, data) ( soap_begin_recv(soap) || !soap_get___icd3__GetDeviceUpdateInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd3__GetDeviceUpdateInfo * SOAP_FMAC4 soap_get___icd3__GetDeviceUpdateInfo(struct soap*, struct __icd3__GetDeviceUpdateInfo *, const char*, const char*);

#define soap_new___icd3__GetDeviceUpdateInfo(soap, n) soap_instantiate___icd3__GetDeviceUpdateInfo(soap, n, NULL, NULL, NULL)


#define soap_delete___icd3__GetDeviceUpdateInfo(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd3__GetDeviceUpdateInfo * SOAP_FMAC2 soap_instantiate___icd3__GetDeviceUpdateInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd3__GetDeviceUpdateInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd3__TestSession
#define SOAP_TYPE___icd3__TestSession (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd3__TestSession(struct soap*, struct __icd3__TestSession *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd3__TestSession(struct soap*, const struct __icd3__TestSession *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd3__TestSession(struct soap*, const char*, int, const struct __icd3__TestSession *, const char*);
SOAP_FMAC3 struct __icd3__TestSession * SOAP_FMAC4 soap_in___icd3__TestSession(struct soap*, const char*, struct __icd3__TestSession *, const char*);

#ifndef soap_write___icd3__TestSession
#define soap_write___icd3__TestSession(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd3__TestSession(soap, data), 0) || soap_put___icd3__TestSession(soap, data, "-icd3:TestSession", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd3__TestSession(struct soap*, const struct __icd3__TestSession *, const char*, const char*);

#ifndef soap_read___icd3__TestSession
#define soap_read___icd3__TestSession(soap, data) ( soap_begin_recv(soap) || !soap_get___icd3__TestSession(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd3__TestSession * SOAP_FMAC4 soap_get___icd3__TestSession(struct soap*, struct __icd3__TestSession *, const char*, const char*);

#define soap_new___icd3__TestSession(soap, n) soap_instantiate___icd3__TestSession(soap, n, NULL, NULL, NULL)


#define soap_delete___icd3__TestSession(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd3__TestSession * SOAP_FMAC2 soap_instantiate___icd3__TestSession(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd3__TestSession(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd3__LogoutDevice
#define SOAP_TYPE___icd3__LogoutDevice (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd3__LogoutDevice(struct soap*, struct __icd3__LogoutDevice *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd3__LogoutDevice(struct soap*, const struct __icd3__LogoutDevice *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd3__LogoutDevice(struct soap*, const char*, int, const struct __icd3__LogoutDevice *, const char*);
SOAP_FMAC3 struct __icd3__LogoutDevice * SOAP_FMAC4 soap_in___icd3__LogoutDevice(struct soap*, const char*, struct __icd3__LogoutDevice *, const char*);

#ifndef soap_write___icd3__LogoutDevice
#define soap_write___icd3__LogoutDevice(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd3__LogoutDevice(soap, data), 0) || soap_put___icd3__LogoutDevice(soap, data, "-icd3:LogoutDevice", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd3__LogoutDevice(struct soap*, const struct __icd3__LogoutDevice *, const char*, const char*);

#ifndef soap_read___icd3__LogoutDevice
#define soap_read___icd3__LogoutDevice(soap, data) ( soap_begin_recv(soap) || !soap_get___icd3__LogoutDevice(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd3__LogoutDevice * SOAP_FMAC4 soap_get___icd3__LogoutDevice(struct soap*, struct __icd3__LogoutDevice *, const char*, const char*);

#define soap_new___icd3__LogoutDevice(soap, n) soap_instantiate___icd3__LogoutDevice(soap, n, NULL, NULL, NULL)


#define soap_delete___icd3__LogoutDevice(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd3__LogoutDevice * SOAP_FMAC2 soap_instantiate___icd3__LogoutDevice(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd3__LogoutDevice(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd3__SendData3
#define SOAP_TYPE___icd3__SendData3 (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd3__SendData3(struct soap*, struct __icd3__SendData3 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd3__SendData3(struct soap*, const struct __icd3__SendData3 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd3__SendData3(struct soap*, const char*, int, const struct __icd3__SendData3 *, const char*);
SOAP_FMAC3 struct __icd3__SendData3 * SOAP_FMAC4 soap_in___icd3__SendData3(struct soap*, const char*, struct __icd3__SendData3 *, const char*);

#ifndef soap_write___icd3__SendData3
#define soap_write___icd3__SendData3(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd3__SendData3(soap, data), 0) || soap_put___icd3__SendData3(soap, data, "-icd3:SendData3", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd3__SendData3(struct soap*, const struct __icd3__SendData3 *, const char*, const char*);

#ifndef soap_read___icd3__SendData3
#define soap_read___icd3__SendData3(soap, data) ( soap_begin_recv(soap) || !soap_get___icd3__SendData3(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd3__SendData3 * SOAP_FMAC4 soap_get___icd3__SendData3(struct soap*, struct __icd3__SendData3 *, const char*, const char*);

#define soap_new___icd3__SendData3(soap, n) soap_instantiate___icd3__SendData3(soap, n, NULL, NULL, NULL)


#define soap_delete___icd3__SendData3(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd3__SendData3 * SOAP_FMAC2 soap_instantiate___icd3__SendData3(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd3__SendData3(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd3__SendData
#define SOAP_TYPE___icd3__SendData (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd3__SendData(struct soap*, struct __icd3__SendData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd3__SendData(struct soap*, const struct __icd3__SendData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd3__SendData(struct soap*, const char*, int, const struct __icd3__SendData *, const char*);
SOAP_FMAC3 struct __icd3__SendData * SOAP_FMAC4 soap_in___icd3__SendData(struct soap*, const char*, struct __icd3__SendData *, const char*);

#ifndef soap_write___icd3__SendData
#define soap_write___icd3__SendData(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd3__SendData(soap, data), 0) || soap_put___icd3__SendData(soap, data, "-icd3:SendData", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd3__SendData(struct soap*, const struct __icd3__SendData *, const char*, const char*);

#ifndef soap_read___icd3__SendData
#define soap_read___icd3__SendData(soap, data) ( soap_begin_recv(soap) || !soap_get___icd3__SendData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd3__SendData * SOAP_FMAC4 soap_get___icd3__SendData(struct soap*, struct __icd3__SendData *, const char*, const char*);

#define soap_new___icd3__SendData(soap, n) soap_instantiate___icd3__SendData(soap, n, NULL, NULL, NULL)


#define soap_delete___icd3__SendData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd3__SendData * SOAP_FMAC2 soap_instantiate___icd3__SendData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd3__SendData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd3__LoginDevice
#define SOAP_TYPE___icd3__LoginDevice (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd3__LoginDevice(struct soap*, struct __icd3__LoginDevice *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd3__LoginDevice(struct soap*, const struct __icd3__LoginDevice *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd3__LoginDevice(struct soap*, const char*, int, const struct __icd3__LoginDevice *, const char*);
SOAP_FMAC3 struct __icd3__LoginDevice * SOAP_FMAC4 soap_in___icd3__LoginDevice(struct soap*, const char*, struct __icd3__LoginDevice *, const char*);

#ifndef soap_write___icd3__LoginDevice
#define soap_write___icd3__LoginDevice(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd3__LoginDevice(soap, data), 0) || soap_put___icd3__LoginDevice(soap, data, "-icd3:LoginDevice", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd3__LoginDevice(struct soap*, const struct __icd3__LoginDevice *, const char*, const char*);

#ifndef soap_read___icd3__LoginDevice
#define soap_read___icd3__LoginDevice(soap, data) ( soap_begin_recv(soap) || !soap_get___icd3__LoginDevice(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd3__LoginDevice * SOAP_FMAC4 soap_get___icd3__LoginDevice(struct soap*, struct __icd3__LoginDevice *, const char*, const char*);

#define soap_new___icd3__LoginDevice(soap, n) soap_instantiate___icd3__LoginDevice(soap, n, NULL, NULL, NULL)


#define soap_delete___icd3__LoginDevice(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd3__LoginDevice * SOAP_FMAC2 soap_instantiate___icd3__LoginDevice(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd3__LoginDevice(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd3__GetTime
#define SOAP_TYPE___icd3__GetTime (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd3__GetTime(struct soap*, struct __icd3__GetTime *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd3__GetTime(struct soap*, const struct __icd3__GetTime *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd3__GetTime(struct soap*, const char*, int, const struct __icd3__GetTime *, const char*);
SOAP_FMAC3 struct __icd3__GetTime * SOAP_FMAC4 soap_in___icd3__GetTime(struct soap*, const char*, struct __icd3__GetTime *, const char*);

#ifndef soap_write___icd3__GetTime
#define soap_write___icd3__GetTime(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd3__GetTime(soap, data), 0) || soap_put___icd3__GetTime(soap, data, "-icd3:GetTime", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd3__GetTime(struct soap*, const struct __icd3__GetTime *, const char*, const char*);

#ifndef soap_read___icd3__GetTime
#define soap_read___icd3__GetTime(soap, data) ( soap_begin_recv(soap) || !soap_get___icd3__GetTime(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd3__GetTime * SOAP_FMAC4 soap_get___icd3__GetTime(struct soap*, struct __icd3__GetTime *, const char*, const char*);

#define soap_new___icd3__GetTime(soap, n) soap_instantiate___icd3__GetTime(soap, n, NULL, NULL, NULL)


#define soap_delete___icd3__GetTime(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd3__GetTime * SOAP_FMAC2 soap_instantiate___icd3__GetTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd3__GetTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd2__GetMacIdd
#define SOAP_TYPE___icd2__GetMacIdd (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd2__GetMacIdd(struct soap*, struct __icd2__GetMacIdd *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd2__GetMacIdd(struct soap*, const struct __icd2__GetMacIdd *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd2__GetMacIdd(struct soap*, const char*, int, const struct __icd2__GetMacIdd *, const char*);
SOAP_FMAC3 struct __icd2__GetMacIdd * SOAP_FMAC4 soap_in___icd2__GetMacIdd(struct soap*, const char*, struct __icd2__GetMacIdd *, const char*);

#ifndef soap_write___icd2__GetMacIdd
#define soap_write___icd2__GetMacIdd(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd2__GetMacIdd(soap, data), 0) || soap_put___icd2__GetMacIdd(soap, data, "-icd2:GetMacIdd", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd2__GetMacIdd(struct soap*, const struct __icd2__GetMacIdd *, const char*, const char*);

#ifndef soap_read___icd2__GetMacIdd
#define soap_read___icd2__GetMacIdd(soap, data) ( soap_begin_recv(soap) || !soap_get___icd2__GetMacIdd(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd2__GetMacIdd * SOAP_FMAC4 soap_get___icd2__GetMacIdd(struct soap*, struct __icd2__GetMacIdd *, const char*, const char*);

#define soap_new___icd2__GetMacIdd(soap, n) soap_instantiate___icd2__GetMacIdd(soap, n, NULL, NULL, NULL)


#define soap_delete___icd2__GetMacIdd(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd2__GetMacIdd * SOAP_FMAC2 soap_instantiate___icd2__GetMacIdd(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd2__GetMacIdd(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd2__GetDeviceUpdateInfo
#define SOAP_TYPE___icd2__GetDeviceUpdateInfo (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd2__GetDeviceUpdateInfo(struct soap*, struct __icd2__GetDeviceUpdateInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd2__GetDeviceUpdateInfo(struct soap*, const struct __icd2__GetDeviceUpdateInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd2__GetDeviceUpdateInfo(struct soap*, const char*, int, const struct __icd2__GetDeviceUpdateInfo *, const char*);
SOAP_FMAC3 struct __icd2__GetDeviceUpdateInfo * SOAP_FMAC4 soap_in___icd2__GetDeviceUpdateInfo(struct soap*, const char*, struct __icd2__GetDeviceUpdateInfo *, const char*);

#ifndef soap_write___icd2__GetDeviceUpdateInfo
#define soap_write___icd2__GetDeviceUpdateInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd2__GetDeviceUpdateInfo(soap, data), 0) || soap_put___icd2__GetDeviceUpdateInfo(soap, data, "-icd2:GetDeviceUpdateInfo", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd2__GetDeviceUpdateInfo(struct soap*, const struct __icd2__GetDeviceUpdateInfo *, const char*, const char*);

#ifndef soap_read___icd2__GetDeviceUpdateInfo
#define soap_read___icd2__GetDeviceUpdateInfo(soap, data) ( soap_begin_recv(soap) || !soap_get___icd2__GetDeviceUpdateInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd2__GetDeviceUpdateInfo * SOAP_FMAC4 soap_get___icd2__GetDeviceUpdateInfo(struct soap*, struct __icd2__GetDeviceUpdateInfo *, const char*, const char*);

#define soap_new___icd2__GetDeviceUpdateInfo(soap, n) soap_instantiate___icd2__GetDeviceUpdateInfo(soap, n, NULL, NULL, NULL)


#define soap_delete___icd2__GetDeviceUpdateInfo(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd2__GetDeviceUpdateInfo * SOAP_FMAC2 soap_instantiate___icd2__GetDeviceUpdateInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd2__GetDeviceUpdateInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd2__TestSession
#define SOAP_TYPE___icd2__TestSession (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd2__TestSession(struct soap*, struct __icd2__TestSession *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd2__TestSession(struct soap*, const struct __icd2__TestSession *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd2__TestSession(struct soap*, const char*, int, const struct __icd2__TestSession *, const char*);
SOAP_FMAC3 struct __icd2__TestSession * SOAP_FMAC4 soap_in___icd2__TestSession(struct soap*, const char*, struct __icd2__TestSession *, const char*);

#ifndef soap_write___icd2__TestSession
#define soap_write___icd2__TestSession(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd2__TestSession(soap, data), 0) || soap_put___icd2__TestSession(soap, data, "-icd2:TestSession", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd2__TestSession(struct soap*, const struct __icd2__TestSession *, const char*, const char*);

#ifndef soap_read___icd2__TestSession
#define soap_read___icd2__TestSession(soap, data) ( soap_begin_recv(soap) || !soap_get___icd2__TestSession(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd2__TestSession * SOAP_FMAC4 soap_get___icd2__TestSession(struct soap*, struct __icd2__TestSession *, const char*, const char*);

#define soap_new___icd2__TestSession(soap, n) soap_instantiate___icd2__TestSession(soap, n, NULL, NULL, NULL)


#define soap_delete___icd2__TestSession(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd2__TestSession * SOAP_FMAC2 soap_instantiate___icd2__TestSession(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd2__TestSession(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd2__LogoutDevice
#define SOAP_TYPE___icd2__LogoutDevice (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd2__LogoutDevice(struct soap*, struct __icd2__LogoutDevice *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd2__LogoutDevice(struct soap*, const struct __icd2__LogoutDevice *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd2__LogoutDevice(struct soap*, const char*, int, const struct __icd2__LogoutDevice *, const char*);
SOAP_FMAC3 struct __icd2__LogoutDevice * SOAP_FMAC4 soap_in___icd2__LogoutDevice(struct soap*, const char*, struct __icd2__LogoutDevice *, const char*);

#ifndef soap_write___icd2__LogoutDevice
#define soap_write___icd2__LogoutDevice(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd2__LogoutDevice(soap, data), 0) || soap_put___icd2__LogoutDevice(soap, data, "-icd2:LogoutDevice", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd2__LogoutDevice(struct soap*, const struct __icd2__LogoutDevice *, const char*, const char*);

#ifndef soap_read___icd2__LogoutDevice
#define soap_read___icd2__LogoutDevice(soap, data) ( soap_begin_recv(soap) || !soap_get___icd2__LogoutDevice(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd2__LogoutDevice * SOAP_FMAC4 soap_get___icd2__LogoutDevice(struct soap*, struct __icd2__LogoutDevice *, const char*, const char*);

#define soap_new___icd2__LogoutDevice(soap, n) soap_instantiate___icd2__LogoutDevice(soap, n, NULL, NULL, NULL)


#define soap_delete___icd2__LogoutDevice(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd2__LogoutDevice * SOAP_FMAC2 soap_instantiate___icd2__LogoutDevice(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd2__LogoutDevice(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd2__SendData3
#define SOAP_TYPE___icd2__SendData3 (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd2__SendData3(struct soap*, struct __icd2__SendData3 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd2__SendData3(struct soap*, const struct __icd2__SendData3 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd2__SendData3(struct soap*, const char*, int, const struct __icd2__SendData3 *, const char*);
SOAP_FMAC3 struct __icd2__SendData3 * SOAP_FMAC4 soap_in___icd2__SendData3(struct soap*, const char*, struct __icd2__SendData3 *, const char*);

#ifndef soap_write___icd2__SendData3
#define soap_write___icd2__SendData3(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd2__SendData3(soap, data), 0) || soap_put___icd2__SendData3(soap, data, "-icd2:SendData3", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd2__SendData3(struct soap*, const struct __icd2__SendData3 *, const char*, const char*);

#ifndef soap_read___icd2__SendData3
#define soap_read___icd2__SendData3(soap, data) ( soap_begin_recv(soap) || !soap_get___icd2__SendData3(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd2__SendData3 * SOAP_FMAC4 soap_get___icd2__SendData3(struct soap*, struct __icd2__SendData3 *, const char*, const char*);

#define soap_new___icd2__SendData3(soap, n) soap_instantiate___icd2__SendData3(soap, n, NULL, NULL, NULL)


#define soap_delete___icd2__SendData3(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd2__SendData3 * SOAP_FMAC2 soap_instantiate___icd2__SendData3(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd2__SendData3(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd2__SendData
#define SOAP_TYPE___icd2__SendData (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd2__SendData(struct soap*, struct __icd2__SendData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd2__SendData(struct soap*, const struct __icd2__SendData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd2__SendData(struct soap*, const char*, int, const struct __icd2__SendData *, const char*);
SOAP_FMAC3 struct __icd2__SendData * SOAP_FMAC4 soap_in___icd2__SendData(struct soap*, const char*, struct __icd2__SendData *, const char*);

#ifndef soap_write___icd2__SendData
#define soap_write___icd2__SendData(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd2__SendData(soap, data), 0) || soap_put___icd2__SendData(soap, data, "-icd2:SendData", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd2__SendData(struct soap*, const struct __icd2__SendData *, const char*, const char*);

#ifndef soap_read___icd2__SendData
#define soap_read___icd2__SendData(soap, data) ( soap_begin_recv(soap) || !soap_get___icd2__SendData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd2__SendData * SOAP_FMAC4 soap_get___icd2__SendData(struct soap*, struct __icd2__SendData *, const char*, const char*);

#define soap_new___icd2__SendData(soap, n) soap_instantiate___icd2__SendData(soap, n, NULL, NULL, NULL)


#define soap_delete___icd2__SendData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd2__SendData * SOAP_FMAC2 soap_instantiate___icd2__SendData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd2__SendData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd2__LoginDevice
#define SOAP_TYPE___icd2__LoginDevice (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd2__LoginDevice(struct soap*, struct __icd2__LoginDevice *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd2__LoginDevice(struct soap*, const struct __icd2__LoginDevice *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd2__LoginDevice(struct soap*, const char*, int, const struct __icd2__LoginDevice *, const char*);
SOAP_FMAC3 struct __icd2__LoginDevice * SOAP_FMAC4 soap_in___icd2__LoginDevice(struct soap*, const char*, struct __icd2__LoginDevice *, const char*);

#ifndef soap_write___icd2__LoginDevice
#define soap_write___icd2__LoginDevice(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd2__LoginDevice(soap, data), 0) || soap_put___icd2__LoginDevice(soap, data, "-icd2:LoginDevice", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd2__LoginDevice(struct soap*, const struct __icd2__LoginDevice *, const char*, const char*);

#ifndef soap_read___icd2__LoginDevice
#define soap_read___icd2__LoginDevice(soap, data) ( soap_begin_recv(soap) || !soap_get___icd2__LoginDevice(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd2__LoginDevice * SOAP_FMAC4 soap_get___icd2__LoginDevice(struct soap*, struct __icd2__LoginDevice *, const char*, const char*);

#define soap_new___icd2__LoginDevice(soap, n) soap_instantiate___icd2__LoginDevice(soap, n, NULL, NULL, NULL)


#define soap_delete___icd2__LoginDevice(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd2__LoginDevice * SOAP_FMAC2 soap_instantiate___icd2__LoginDevice(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd2__LoginDevice(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___icd2__GetTime
#define SOAP_TYPE___icd2__GetTime (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___icd2__GetTime(struct soap*, struct __icd2__GetTime *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___icd2__GetTime(struct soap*, const struct __icd2__GetTime *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___icd2__GetTime(struct soap*, const char*, int, const struct __icd2__GetTime *, const char*);
SOAP_FMAC3 struct __icd2__GetTime * SOAP_FMAC4 soap_in___icd2__GetTime(struct soap*, const char*, struct __icd2__GetTime *, const char*);

#ifndef soap_write___icd2__GetTime
#define soap_write___icd2__GetTime(soap, data) ( soap_begin_send(soap) || (soap_serialize___icd2__GetTime(soap, data), 0) || soap_put___icd2__GetTime(soap, data, "-icd2:GetTime", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___icd2__GetTime(struct soap*, const struct __icd2__GetTime *, const char*, const char*);

#ifndef soap_read___icd2__GetTime
#define soap_read___icd2__GetTime(soap, data) ( soap_begin_recv(soap) || !soap_get___icd2__GetTime(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __icd2__GetTime * SOAP_FMAC4 soap_get___icd2__GetTime(struct soap*, struct __icd2__GetTime *, const char*, const char*);

#define soap_new___icd2__GetTime(soap, n) soap_instantiate___icd2__GetTime(soap, n, NULL, NULL, NULL)


#define soap_delete___icd2__GetTime(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __icd2__GetTime * SOAP_FMAC2 soap_instantiate___icd2__GetTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___icd2__GetTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (88)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (87)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_icd1__GetMacIddResponse
#define SOAP_TYPE_PointerTo_icd1__GetMacIddResponse (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__GetMacIddResponse(struct soap*, _icd1__GetMacIddResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__GetMacIddResponse(struct soap*, const char *, int, _icd1__GetMacIddResponse *const*, const char *);
SOAP_FMAC3 _icd1__GetMacIddResponse ** SOAP_FMAC4 soap_in_PointerTo_icd1__GetMacIddResponse(struct soap*, const char*, _icd1__GetMacIddResponse **, const char*);

#ifndef soap_write_PointerTo_icd1__GetMacIddResponse
#define soap_write_PointerTo_icd1__GetMacIddResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__GetMacIddResponse(soap, data), 0) || soap_put_PointerTo_icd1__GetMacIddResponse(soap, data, "icd1:GetMacIddResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__GetMacIddResponse(struct soap*, _icd1__GetMacIddResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__GetMacIddResponse
#define soap_read_PointerTo_icd1__GetMacIddResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__GetMacIddResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__GetMacIddResponse ** SOAP_FMAC4 soap_get_PointerTo_icd1__GetMacIddResponse(struct soap*, _icd1__GetMacIddResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__GetMacIdd
#define SOAP_TYPE_PointerTo_icd1__GetMacIdd (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__GetMacIdd(struct soap*, _icd1__GetMacIdd *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__GetMacIdd(struct soap*, const char *, int, _icd1__GetMacIdd *const*, const char *);
SOAP_FMAC3 _icd1__GetMacIdd ** SOAP_FMAC4 soap_in_PointerTo_icd1__GetMacIdd(struct soap*, const char*, _icd1__GetMacIdd **, const char*);

#ifndef soap_write_PointerTo_icd1__GetMacIdd
#define soap_write_PointerTo_icd1__GetMacIdd(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__GetMacIdd(soap, data), 0) || soap_put_PointerTo_icd1__GetMacIdd(soap, data, "icd1:GetMacIdd", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__GetMacIdd(struct soap*, _icd1__GetMacIdd *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__GetMacIdd
#define soap_read_PointerTo_icd1__GetMacIdd(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__GetMacIdd(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__GetMacIdd ** SOAP_FMAC4 soap_get_PointerTo_icd1__GetMacIdd(struct soap*, _icd1__GetMacIdd **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__GetDeviceUpdateInfoResponse
#define SOAP_TYPE_PointerTo_icd1__GetDeviceUpdateInfoResponse (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__GetDeviceUpdateInfoResponse(struct soap*, _icd1__GetDeviceUpdateInfoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__GetDeviceUpdateInfoResponse(struct soap*, const char *, int, _icd1__GetDeviceUpdateInfoResponse *const*, const char *);
SOAP_FMAC3 _icd1__GetDeviceUpdateInfoResponse ** SOAP_FMAC4 soap_in_PointerTo_icd1__GetDeviceUpdateInfoResponse(struct soap*, const char*, _icd1__GetDeviceUpdateInfoResponse **, const char*);

#ifndef soap_write_PointerTo_icd1__GetDeviceUpdateInfoResponse
#define soap_write_PointerTo_icd1__GetDeviceUpdateInfoResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__GetDeviceUpdateInfoResponse(soap, data), 0) || soap_put_PointerTo_icd1__GetDeviceUpdateInfoResponse(soap, data, "icd1:GetDeviceUpdateInfoResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__GetDeviceUpdateInfoResponse(struct soap*, _icd1__GetDeviceUpdateInfoResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__GetDeviceUpdateInfoResponse
#define soap_read_PointerTo_icd1__GetDeviceUpdateInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__GetDeviceUpdateInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__GetDeviceUpdateInfoResponse ** SOAP_FMAC4 soap_get_PointerTo_icd1__GetDeviceUpdateInfoResponse(struct soap*, _icd1__GetDeviceUpdateInfoResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__GetDeviceUpdateInfo
#define SOAP_TYPE_PointerTo_icd1__GetDeviceUpdateInfo (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__GetDeviceUpdateInfo(struct soap*, _icd1__GetDeviceUpdateInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__GetDeviceUpdateInfo(struct soap*, const char *, int, _icd1__GetDeviceUpdateInfo *const*, const char *);
SOAP_FMAC3 _icd1__GetDeviceUpdateInfo ** SOAP_FMAC4 soap_in_PointerTo_icd1__GetDeviceUpdateInfo(struct soap*, const char*, _icd1__GetDeviceUpdateInfo **, const char*);

#ifndef soap_write_PointerTo_icd1__GetDeviceUpdateInfo
#define soap_write_PointerTo_icd1__GetDeviceUpdateInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__GetDeviceUpdateInfo(soap, data), 0) || soap_put_PointerTo_icd1__GetDeviceUpdateInfo(soap, data, "icd1:GetDeviceUpdateInfo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__GetDeviceUpdateInfo(struct soap*, _icd1__GetDeviceUpdateInfo *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__GetDeviceUpdateInfo
#define soap_read_PointerTo_icd1__GetDeviceUpdateInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__GetDeviceUpdateInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__GetDeviceUpdateInfo ** SOAP_FMAC4 soap_get_PointerTo_icd1__GetDeviceUpdateInfo(struct soap*, _icd1__GetDeviceUpdateInfo **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__TestSessionResponse
#define SOAP_TYPE_PointerTo_icd1__TestSessionResponse (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__TestSessionResponse(struct soap*, _icd1__TestSessionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__TestSessionResponse(struct soap*, const char *, int, _icd1__TestSessionResponse *const*, const char *);
SOAP_FMAC3 _icd1__TestSessionResponse ** SOAP_FMAC4 soap_in_PointerTo_icd1__TestSessionResponse(struct soap*, const char*, _icd1__TestSessionResponse **, const char*);

#ifndef soap_write_PointerTo_icd1__TestSessionResponse
#define soap_write_PointerTo_icd1__TestSessionResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__TestSessionResponse(soap, data), 0) || soap_put_PointerTo_icd1__TestSessionResponse(soap, data, "icd1:TestSessionResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__TestSessionResponse(struct soap*, _icd1__TestSessionResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__TestSessionResponse
#define soap_read_PointerTo_icd1__TestSessionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__TestSessionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__TestSessionResponse ** SOAP_FMAC4 soap_get_PointerTo_icd1__TestSessionResponse(struct soap*, _icd1__TestSessionResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__TestSession
#define SOAP_TYPE_PointerTo_icd1__TestSession (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__TestSession(struct soap*, _icd1__TestSession *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__TestSession(struct soap*, const char *, int, _icd1__TestSession *const*, const char *);
SOAP_FMAC3 _icd1__TestSession ** SOAP_FMAC4 soap_in_PointerTo_icd1__TestSession(struct soap*, const char*, _icd1__TestSession **, const char*);

#ifndef soap_write_PointerTo_icd1__TestSession
#define soap_write_PointerTo_icd1__TestSession(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__TestSession(soap, data), 0) || soap_put_PointerTo_icd1__TestSession(soap, data, "icd1:TestSession", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__TestSession(struct soap*, _icd1__TestSession *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__TestSession
#define soap_read_PointerTo_icd1__TestSession(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__TestSession(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__TestSession ** SOAP_FMAC4 soap_get_PointerTo_icd1__TestSession(struct soap*, _icd1__TestSession **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__LogoutDeviceResponse
#define SOAP_TYPE_PointerTo_icd1__LogoutDeviceResponse (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__LogoutDeviceResponse(struct soap*, _icd1__LogoutDeviceResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__LogoutDeviceResponse(struct soap*, const char *, int, _icd1__LogoutDeviceResponse *const*, const char *);
SOAP_FMAC3 _icd1__LogoutDeviceResponse ** SOAP_FMAC4 soap_in_PointerTo_icd1__LogoutDeviceResponse(struct soap*, const char*, _icd1__LogoutDeviceResponse **, const char*);

#ifndef soap_write_PointerTo_icd1__LogoutDeviceResponse
#define soap_write_PointerTo_icd1__LogoutDeviceResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__LogoutDeviceResponse(soap, data), 0) || soap_put_PointerTo_icd1__LogoutDeviceResponse(soap, data, "icd1:LogoutDeviceResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__LogoutDeviceResponse(struct soap*, _icd1__LogoutDeviceResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__LogoutDeviceResponse
#define soap_read_PointerTo_icd1__LogoutDeviceResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__LogoutDeviceResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__LogoutDeviceResponse ** SOAP_FMAC4 soap_get_PointerTo_icd1__LogoutDeviceResponse(struct soap*, _icd1__LogoutDeviceResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__LogoutDevice
#define SOAP_TYPE_PointerTo_icd1__LogoutDevice (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__LogoutDevice(struct soap*, _icd1__LogoutDevice *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__LogoutDevice(struct soap*, const char *, int, _icd1__LogoutDevice *const*, const char *);
SOAP_FMAC3 _icd1__LogoutDevice ** SOAP_FMAC4 soap_in_PointerTo_icd1__LogoutDevice(struct soap*, const char*, _icd1__LogoutDevice **, const char*);

#ifndef soap_write_PointerTo_icd1__LogoutDevice
#define soap_write_PointerTo_icd1__LogoutDevice(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__LogoutDevice(soap, data), 0) || soap_put_PointerTo_icd1__LogoutDevice(soap, data, "icd1:LogoutDevice", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__LogoutDevice(struct soap*, _icd1__LogoutDevice *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__LogoutDevice
#define soap_read_PointerTo_icd1__LogoutDevice(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__LogoutDevice(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__LogoutDevice ** SOAP_FMAC4 soap_get_PointerTo_icd1__LogoutDevice(struct soap*, _icd1__LogoutDevice **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__SendData3Response
#define SOAP_TYPE_PointerTo_icd1__SendData3Response (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__SendData3Response(struct soap*, _icd1__SendData3Response *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__SendData3Response(struct soap*, const char *, int, _icd1__SendData3Response *const*, const char *);
SOAP_FMAC3 _icd1__SendData3Response ** SOAP_FMAC4 soap_in_PointerTo_icd1__SendData3Response(struct soap*, const char*, _icd1__SendData3Response **, const char*);

#ifndef soap_write_PointerTo_icd1__SendData3Response
#define soap_write_PointerTo_icd1__SendData3Response(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__SendData3Response(soap, data), 0) || soap_put_PointerTo_icd1__SendData3Response(soap, data, "icd1:SendData3Response", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__SendData3Response(struct soap*, _icd1__SendData3Response *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__SendData3Response
#define soap_read_PointerTo_icd1__SendData3Response(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__SendData3Response(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__SendData3Response ** SOAP_FMAC4 soap_get_PointerTo_icd1__SendData3Response(struct soap*, _icd1__SendData3Response **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__SendData3
#define SOAP_TYPE_PointerTo_icd1__SendData3 (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__SendData3(struct soap*, _icd1__SendData3 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__SendData3(struct soap*, const char *, int, _icd1__SendData3 *const*, const char *);
SOAP_FMAC3 _icd1__SendData3 ** SOAP_FMAC4 soap_in_PointerTo_icd1__SendData3(struct soap*, const char*, _icd1__SendData3 **, const char*);

#ifndef soap_write_PointerTo_icd1__SendData3
#define soap_write_PointerTo_icd1__SendData3(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__SendData3(soap, data), 0) || soap_put_PointerTo_icd1__SendData3(soap, data, "icd1:SendData3", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__SendData3(struct soap*, _icd1__SendData3 *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__SendData3
#define soap_read_PointerTo_icd1__SendData3(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__SendData3(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__SendData3 ** SOAP_FMAC4 soap_get_PointerTo_icd1__SendData3(struct soap*, _icd1__SendData3 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__SendDataResponse
#define SOAP_TYPE_PointerTo_icd1__SendDataResponse (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__SendDataResponse(struct soap*, _icd1__SendDataResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__SendDataResponse(struct soap*, const char *, int, _icd1__SendDataResponse *const*, const char *);
SOAP_FMAC3 _icd1__SendDataResponse ** SOAP_FMAC4 soap_in_PointerTo_icd1__SendDataResponse(struct soap*, const char*, _icd1__SendDataResponse **, const char*);

#ifndef soap_write_PointerTo_icd1__SendDataResponse
#define soap_write_PointerTo_icd1__SendDataResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__SendDataResponse(soap, data), 0) || soap_put_PointerTo_icd1__SendDataResponse(soap, data, "icd1:SendDataResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__SendDataResponse(struct soap*, _icd1__SendDataResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__SendDataResponse
#define soap_read_PointerTo_icd1__SendDataResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__SendDataResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__SendDataResponse ** SOAP_FMAC4 soap_get_PointerTo_icd1__SendDataResponse(struct soap*, _icd1__SendDataResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__SendData
#define SOAP_TYPE_PointerTo_icd1__SendData (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__SendData(struct soap*, _icd1__SendData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__SendData(struct soap*, const char *, int, _icd1__SendData *const*, const char *);
SOAP_FMAC3 _icd1__SendData ** SOAP_FMAC4 soap_in_PointerTo_icd1__SendData(struct soap*, const char*, _icd1__SendData **, const char*);

#ifndef soap_write_PointerTo_icd1__SendData
#define soap_write_PointerTo_icd1__SendData(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__SendData(soap, data), 0) || soap_put_PointerTo_icd1__SendData(soap, data, "icd1:SendData", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__SendData(struct soap*, _icd1__SendData *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__SendData
#define soap_read_PointerTo_icd1__SendData(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__SendData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__SendData ** SOAP_FMAC4 soap_get_PointerTo_icd1__SendData(struct soap*, _icd1__SendData **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__LoginDeviceResponse
#define SOAP_TYPE_PointerTo_icd1__LoginDeviceResponse (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__LoginDeviceResponse(struct soap*, _icd1__LoginDeviceResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__LoginDeviceResponse(struct soap*, const char *, int, _icd1__LoginDeviceResponse *const*, const char *);
SOAP_FMAC3 _icd1__LoginDeviceResponse ** SOAP_FMAC4 soap_in_PointerTo_icd1__LoginDeviceResponse(struct soap*, const char*, _icd1__LoginDeviceResponse **, const char*);

#ifndef soap_write_PointerTo_icd1__LoginDeviceResponse
#define soap_write_PointerTo_icd1__LoginDeviceResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__LoginDeviceResponse(soap, data), 0) || soap_put_PointerTo_icd1__LoginDeviceResponse(soap, data, "icd1:LoginDeviceResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__LoginDeviceResponse(struct soap*, _icd1__LoginDeviceResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__LoginDeviceResponse
#define soap_read_PointerTo_icd1__LoginDeviceResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__LoginDeviceResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__LoginDeviceResponse ** SOAP_FMAC4 soap_get_PointerTo_icd1__LoginDeviceResponse(struct soap*, _icd1__LoginDeviceResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__LoginDevice
#define SOAP_TYPE_PointerTo_icd1__LoginDevice (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__LoginDevice(struct soap*, _icd1__LoginDevice *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__LoginDevice(struct soap*, const char *, int, _icd1__LoginDevice *const*, const char *);
SOAP_FMAC3 _icd1__LoginDevice ** SOAP_FMAC4 soap_in_PointerTo_icd1__LoginDevice(struct soap*, const char*, _icd1__LoginDevice **, const char*);

#ifndef soap_write_PointerTo_icd1__LoginDevice
#define soap_write_PointerTo_icd1__LoginDevice(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__LoginDevice(soap, data), 0) || soap_put_PointerTo_icd1__LoginDevice(soap, data, "icd1:LoginDevice", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__LoginDevice(struct soap*, _icd1__LoginDevice *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__LoginDevice
#define soap_read_PointerTo_icd1__LoginDevice(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__LoginDevice(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__LoginDevice ** SOAP_FMAC4 soap_get_PointerTo_icd1__LoginDevice(struct soap*, _icd1__LoginDevice **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__GetTimeResponse
#define SOAP_TYPE_PointerTo_icd1__GetTimeResponse (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__GetTimeResponse(struct soap*, _icd1__GetTimeResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__GetTimeResponse(struct soap*, const char *, int, _icd1__GetTimeResponse *const*, const char *);
SOAP_FMAC3 _icd1__GetTimeResponse ** SOAP_FMAC4 soap_in_PointerTo_icd1__GetTimeResponse(struct soap*, const char*, _icd1__GetTimeResponse **, const char*);

#ifndef soap_write_PointerTo_icd1__GetTimeResponse
#define soap_write_PointerTo_icd1__GetTimeResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__GetTimeResponse(soap, data), 0) || soap_put_PointerTo_icd1__GetTimeResponse(soap, data, "icd1:GetTimeResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__GetTimeResponse(struct soap*, _icd1__GetTimeResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__GetTimeResponse
#define soap_read_PointerTo_icd1__GetTimeResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__GetTimeResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__GetTimeResponse ** SOAP_FMAC4 soap_get_PointerTo_icd1__GetTimeResponse(struct soap*, _icd1__GetTimeResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_icd1__GetTime
#define SOAP_TYPE_PointerTo_icd1__GetTime (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_icd1__GetTime(struct soap*, _icd1__GetTime *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_icd1__GetTime(struct soap*, const char *, int, _icd1__GetTime *const*, const char *);
SOAP_FMAC3 _icd1__GetTime ** SOAP_FMAC4 soap_in_PointerTo_icd1__GetTime(struct soap*, const char*, _icd1__GetTime **, const char*);

#ifndef soap_write_PointerTo_icd1__GetTime
#define soap_write_PointerTo_icd1__GetTime(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_icd1__GetTime(soap, data), 0) || soap_put_PointerTo_icd1__GetTime(soap, data, "icd1:GetTime", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_icd1__GetTime(struct soap*, _icd1__GetTime *const*, const char*, const char*);

#ifndef soap_read_PointerTo_icd1__GetTime
#define soap_read_PointerTo_icd1__GetTime(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_icd1__GetTime(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _icd1__GetTime ** SOAP_FMAC4 soap_get_PointerTo_icd1__GetTime(struct soap*, _icd1__GetTime **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToicd1__GetMacIddPack
#define SOAP_TYPE_PointerToicd1__GetMacIddPack (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToicd1__GetMacIddPack(struct soap*, icd1__GetMacIddPack *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToicd1__GetMacIddPack(struct soap*, const char *, int, icd1__GetMacIddPack *const*, const char *);
SOAP_FMAC3 icd1__GetMacIddPack ** SOAP_FMAC4 soap_in_PointerToicd1__GetMacIddPack(struct soap*, const char*, icd1__GetMacIddPack **, const char*);

#ifndef soap_write_PointerToicd1__GetMacIddPack
#define soap_write_PointerToicd1__GetMacIddPack(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToicd1__GetMacIddPack(soap, data), 0) || soap_put_PointerToicd1__GetMacIddPack(soap, data, "icd1:GetMacIddPack", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToicd1__GetMacIddPack(struct soap*, icd1__GetMacIddPack *const*, const char*, const char*);

#ifndef soap_read_PointerToicd1__GetMacIddPack
#define soap_read_PointerToicd1__GetMacIddPack(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToicd1__GetMacIddPack(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 icd1__GetMacIddPack ** SOAP_FMAC4 soap_get_PointerToicd1__GetMacIddPack(struct soap*, icd1__GetMacIddPack **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToicd1__UpdatePack
#define SOAP_TYPE_PointerToicd1__UpdatePack (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToicd1__UpdatePack(struct soap*, icd1__UpdatePack *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToicd1__UpdatePack(struct soap*, const char *, int, icd1__UpdatePack *const*, const char *);
SOAP_FMAC3 icd1__UpdatePack ** SOAP_FMAC4 soap_in_PointerToicd1__UpdatePack(struct soap*, const char*, icd1__UpdatePack **, const char*);

#ifndef soap_write_PointerToicd1__UpdatePack
#define soap_write_PointerToicd1__UpdatePack(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToicd1__UpdatePack(soap, data), 0) || soap_put_PointerToicd1__UpdatePack(soap, data, "icd1:UpdatePack", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToicd1__UpdatePack(struct soap*, icd1__UpdatePack *const*, const char*, const char*);

#ifndef soap_read_PointerToicd1__UpdatePack
#define soap_read_PointerToicd1__UpdatePack(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToicd1__UpdatePack(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 icd1__UpdatePack ** SOAP_FMAC4 soap_get_PointerToicd1__UpdatePack(struct soap*, icd1__UpdatePack **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef soap_write_PointerTostd__string
#define soap_write_PointerTostd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTostd__string(soap, data), 0) || soap_put_PointerTostd__string(soap, data, "string", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);

#ifndef soap_read_PointerTostd__string
#define soap_read_PointerTostd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of H.h */
