/* schem.h
   Generated by wsdl2h 2.8.8 from schem.wsdl and typemap.dat
   2012-09-06 12:36:13 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2001-2012 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on schem.h to generate the SOAP/XML processing logic.
   Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 option -i to generate improved proxy and server classes.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h options -nname and -Nname to globally rename the prefix 'ns'.
 - Use wsdl2h option -d to enable DOM support for xsd:anyType.
 - Use wsdl2h option -g to auto-generate readers and writers for root elements.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS.
   USE THE SOURCE CODE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT BUILDS:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
1) GPL or 2) Genivia's license for commercial use.
--------------------------------------------------------------------------------
1) GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
2) A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://insofter.pl/webservices                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to remove STL dependency)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/

// This service uses SOAP 1.2 namespaces:
//gsoap SOAP-ENV schema namespace:	http://www.w3.org/2003/05/soap-envelope
//gsoap SOAP-ENC schema namespace:	http://www.w3.org/2003/05/soap-encoding

/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

icd1 = "http://insofter.pl/webservices"

*/

#define SOAP_NAMESPACE_OF_icd1	"http://insofter.pl/webservices"
//gsoap icd1  schema namespace:	http://insofter.pl/webservices
//gsoap icd1  schema elementForm:	qualified
//gsoap icd1  schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/



//  Forward declaration of class _icd1__GetTime.
class _icd1__GetTime;

//  Forward declaration of class _icd1__GetTimeResponse.
class _icd1__GetTimeResponse;

//  Forward declaration of class _icd1__LoginDevice.
class _icd1__LoginDevice;

//  Forward declaration of class _icd1__LoginDeviceResponse.
class _icd1__LoginDeviceResponse;

//  Forward declaration of class _icd1__SendData.
class _icd1__SendData;

//  Forward declaration of class _icd1__SendDataResponse.
class _icd1__SendDataResponse;

//  Forward declaration of class _icd1__LogoutDevice.
class _icd1__LogoutDevice;

//  Forward declaration of class _icd1__LogoutDeviceResponse.
class _icd1__LogoutDeviceResponse;

/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://insofter.pl/webservices                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://insofter.pl/webservices                                           *
 *                                                                            *
\******************************************************************************/



/// Top-level root element "http://insofter.pl/webservices":GetTime

/// "http://insofter.pl/webservices":GetTime is a complexType.
class _icd1__GetTime
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://insofter.pl/webservices":GetTimeResponse

/// "http://insofter.pl/webservices":GetTimeResponse is a complexType.
class _icd1__GetTimeResponse
{ public:
/// Element GetTimeResult of type xs:string.
    std::string*                         GetTimeResult                  0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://insofter.pl/webservices":LoginDevice

/// "http://insofter.pl/webservices":LoginDevice is a complexType.
class _icd1__LoginDevice
{ public:
/// Element idd of type xs:int.
    int                                  idd                            1;	///< Required element.
/// Element name of type xs:string.
    std::string*                         name                           0;	///< Optional element.
/// Element devInfo of type xs:string.
    std::string*                         devInfo                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://insofter.pl/webservices":LoginDeviceResponse

/// "http://insofter.pl/webservices":LoginDeviceResponse is a complexType.
class _icd1__LoginDeviceResponse
{ public:
/// Element LoginDeviceResult of type xs:int.
    int                                  LoginDeviceResult              1;	///< Required element.
/// Element message of type xs:string.
    std::string*                         message                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://insofter.pl/webservices":SendData

/// "http://insofter.pl/webservices":SendData is a complexType.
class _icd1__SendData
{ public:
/// Element data of type xs:string.
    std::string*                         data                           0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://insofter.pl/webservices":SendDataResponse

/// "http://insofter.pl/webservices":SendDataResponse is a complexType.
class _icd1__SendDataResponse
{ public:
/// Element SendDataResult of type xs:int.
    int                                  SendDataResult                 1;	///< Required element.
/// Element message of type xs:string.
    std::string*                         message                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://insofter.pl/webservices":LogoutDevice

/// "http://insofter.pl/webservices":LogoutDevice is a complexType.
class _icd1__LogoutDevice
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://insofter.pl/webservices":LogoutDeviceResponse

/// "http://insofter.pl/webservices":LogoutDeviceResponse is a complexType.
class _icd1__LogoutDeviceResponse
{ public:
/// Element LogoutDeviceResult of type xs:int.
    int                                  LogoutDeviceResult             1;	///< Required element.
/// Element message of type xs:string.
    std::string*                         message                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://insofter.pl/webservices                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://insofter.pl/webservices                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap icd2 service name:	icdtcp3Soap 
//gsoap icd2 service type:	icdtcp3Soap 
//gsoap icd2 service port:	http://192.168.123.194/icdtcp3/icdtcp3.asmx 
//gsoap icd2 service namespace:	http://insofter.pl/webservices/icdtcp3Soap 
//gsoap icd2 service transport:	http://schemas.xmlsoap.org/soap/http 

//gsoap icd3 service name:	icdtcp3Soap12 
//gsoap icd3 service type:	icdtcp3Soap 
//gsoap icd3 service port:	http://192.168.123.194/icdtcp3/icdtcp3.asmx 
//gsoap icd3 service namespace:	http://insofter.pl/webservices/icdtcp3Soap12 
//gsoap icd3 service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref icdtcp3Soap

  - @ref icdtcp3Soap12

@section Service_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page icdtcp3Soap Binding "icdtcp3Soap"

@section icdtcp3Soap_operations Operations of Binding  "icdtcp3Soap"

  - @ref __icd2__GetTime

  - @ref __icd2__LoginDevice

  - @ref __icd2__SendData

  - @ref __icd2__LogoutDevice

@section icdtcp3Soap_ports Endpoints of Binding  "icdtcp3Soap"

  - http://192.168.123.194/icdtcp3/icdtcp3.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/**

@page icdtcp3Soap12 Binding "icdtcp3Soap12"

@section icdtcp3Soap12_operations Operations of Binding  "icdtcp3Soap12"

  - @ref __icd3__GetTime

  - @ref __icd3__LoginDevice

  - @ref __icd3__SendData

  - @ref __icd3__LogoutDevice

@section icdtcp3Soap12_ports Endpoints of Binding  "icdtcp3Soap12"

  - http://192.168.123.194/icdtcp3/icdtcp3.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   icdtcp3Soap                                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __icd2__GetTime                                                          *
 *                                                                            *
\******************************************************************************/


/// Operation "__icd2__GetTime" of service binding "icdtcp3Soap"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://insofter.pl/webservices/GetTime"

  - Addressing action: "http://insofter.pl/webservices/icdtcp3Soap/GetTime"

  - Addressing response action: "http://insofter.pl/webservices/icdtcp3Soap/GetTimeResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___icd2__GetTime(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _icd1__GetTime*                     icd1__GetTime,
    // response parameters:
    _icd1__GetTimeResponse*             icd1__GetTimeResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __icd2__GetTime(
    struct soap *soap,
    // request parameters:
    _icd1__GetTime*                     icd1__GetTime,
    // response parameters:
    _icd1__GetTimeResponse*             icd1__GetTimeResponse
  );
@endcode

C++ proxy class (defined in soapicdtcp3SoapProxy.h):
@code
  class icdtcp3SoapProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapicdtcp3SoapService.h):
@code
  class icdtcp3SoapService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap icd2 service method-style:	GetTime document
//gsoap icd2 service method-encoding:	GetTime literal
//gsoap icd2 service method-action:	GetTime http://insofter.pl/webservices/GetTime
//gsoap icd2 service method-output-action:	GetTime http://insofter.pl/webservices/icdtcp3Soap/GetTimeResponse
int __icd2__GetTime(
    _icd1__GetTime*                     icd1__GetTime,	///< Request parameter
    _icd1__GetTimeResponse*             icd1__GetTimeResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __icd2__LoginDevice                                                      *
 *                                                                            *
\******************************************************************************/


/// Operation "__icd2__LoginDevice" of service binding "icdtcp3Soap"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://insofter.pl/webservices/LoginDevice"

  - Addressing action: "http://insofter.pl/webservices/icdtcp3Soap/LoginDevice"

  - Addressing response action: "http://insofter.pl/webservices/icdtcp3Soap/LoginDeviceResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___icd2__LoginDevice(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _icd1__LoginDevice*                 icd1__LoginDevice,
    // response parameters:
    _icd1__LoginDeviceResponse*         icd1__LoginDeviceResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __icd2__LoginDevice(
    struct soap *soap,
    // request parameters:
    _icd1__LoginDevice*                 icd1__LoginDevice,
    // response parameters:
    _icd1__LoginDeviceResponse*         icd1__LoginDeviceResponse
  );
@endcode

C++ proxy class (defined in soapicdtcp3SoapProxy.h):
@code
  class icdtcp3SoapProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapicdtcp3SoapService.h):
@code
  class icdtcp3SoapService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap icd2 service method-style:	LoginDevice document
//gsoap icd2 service method-encoding:	LoginDevice literal
//gsoap icd2 service method-action:	LoginDevice http://insofter.pl/webservices/LoginDevice
//gsoap icd2 service method-output-action:	LoginDevice http://insofter.pl/webservices/icdtcp3Soap/LoginDeviceResponse
int __icd2__LoginDevice(
    _icd1__LoginDevice*                 icd1__LoginDevice,	///< Request parameter
    _icd1__LoginDeviceResponse*         icd1__LoginDeviceResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __icd2__SendData                                                         *
 *                                                                            *
\******************************************************************************/


/// Operation "__icd2__SendData" of service binding "icdtcp3Soap"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://insofter.pl/webservices/SendData"

  - Addressing action: "http://insofter.pl/webservices/icdtcp3Soap/SendData"

  - Addressing response action: "http://insofter.pl/webservices/icdtcp3Soap/SendDataResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___icd2__SendData(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _icd1__SendData*                    icd1__SendData,
    // response parameters:
    _icd1__SendDataResponse*            icd1__SendDataResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __icd2__SendData(
    struct soap *soap,
    // request parameters:
    _icd1__SendData*                    icd1__SendData,
    // response parameters:
    _icd1__SendDataResponse*            icd1__SendDataResponse
  );
@endcode

C++ proxy class (defined in soapicdtcp3SoapProxy.h):
@code
  class icdtcp3SoapProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapicdtcp3SoapService.h):
@code
  class icdtcp3SoapService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap icd2 service method-style:	SendData document
//gsoap icd2 service method-encoding:	SendData literal
//gsoap icd2 service method-action:	SendData http://insofter.pl/webservices/SendData
//gsoap icd2 service method-output-action:	SendData http://insofter.pl/webservices/icdtcp3Soap/SendDataResponse
int __icd2__SendData(
    _icd1__SendData*                    icd1__SendData,	///< Request parameter
    _icd1__SendDataResponse*            icd1__SendDataResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __icd2__LogoutDevice                                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "__icd2__LogoutDevice" of service binding "icdtcp3Soap"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://insofter.pl/webservices/LogoutDevice"

  - Addressing action: "http://insofter.pl/webservices/icdtcp3Soap/LogoutDevice"

  - Addressing response action: "http://insofter.pl/webservices/icdtcp3Soap/LogoutDeviceResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___icd2__LogoutDevice(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _icd1__LogoutDevice*                icd1__LogoutDevice,
    // response parameters:
    _icd1__LogoutDeviceResponse*        icd1__LogoutDeviceResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __icd2__LogoutDevice(
    struct soap *soap,
    // request parameters:
    _icd1__LogoutDevice*                icd1__LogoutDevice,
    // response parameters:
    _icd1__LogoutDeviceResponse*        icd1__LogoutDeviceResponse
  );
@endcode

C++ proxy class (defined in soapicdtcp3SoapProxy.h):
@code
  class icdtcp3SoapProxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapicdtcp3SoapService.h):
@code
  class icdtcp3SoapService;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap icd2 service method-style:	LogoutDevice document
//gsoap icd2 service method-encoding:	LogoutDevice literal
//gsoap icd2 service method-action:	LogoutDevice http://insofter.pl/webservices/LogoutDevice
//gsoap icd2 service method-output-action:	LogoutDevice http://insofter.pl/webservices/icdtcp3Soap/LogoutDeviceResponse
int __icd2__LogoutDevice(
    _icd1__LogoutDevice*                icd1__LogoutDevice,	///< Request parameter
    _icd1__LogoutDeviceResponse*        icd1__LogoutDeviceResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   icdtcp3Soap12                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __icd3__GetTime                                                          *
 *                                                                            *
\******************************************************************************/


/// Operation "__icd3__GetTime" of service binding "icdtcp3Soap12"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://insofter.pl/webservices/GetTime"

  - Addressing action: "http://insofter.pl/webservices/icdtcp3Soap/GetTime"

  - Addressing response action: "http://insofter.pl/webservices/icdtcp3Soap/GetTimeResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___icd3__GetTime(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _icd1__GetTime*                     icd1__GetTime,
    // response parameters:
    _icd1__GetTimeResponse*             icd1__GetTimeResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __icd3__GetTime(
    struct soap *soap,
    // request parameters:
    _icd1__GetTime*                     icd1__GetTime,
    // response parameters:
    _icd1__GetTimeResponse*             icd1__GetTimeResponse
  );
@endcode

C++ proxy class (defined in soapicdtcp3Soap12Proxy.h):
@code
  class icdtcp3Soap12Proxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapicdtcp3Soap12Service.h):
@code
  class icdtcp3Soap12Service;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap icd3 service method-style:	GetTime document
//gsoap icd3 service method-encoding:	GetTime literal
//gsoap icd3 service method-action:	GetTime http://insofter.pl/webservices/GetTime
//gsoap icd3 service method-output-action:	GetTime http://insofter.pl/webservices/icdtcp3Soap/GetTimeResponse
int __icd3__GetTime(
    _icd1__GetTime*                     icd1__GetTime,	///< Request parameter
    _icd1__GetTimeResponse*             icd1__GetTimeResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __icd3__LoginDevice                                                      *
 *                                                                            *
\******************************************************************************/


/// Operation "__icd3__LoginDevice" of service binding "icdtcp3Soap12"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://insofter.pl/webservices/LoginDevice"

  - Addressing action: "http://insofter.pl/webservices/icdtcp3Soap/LoginDevice"

  - Addressing response action: "http://insofter.pl/webservices/icdtcp3Soap/LoginDeviceResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___icd3__LoginDevice(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _icd1__LoginDevice*                 icd1__LoginDevice,
    // response parameters:
    _icd1__LoginDeviceResponse*         icd1__LoginDeviceResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __icd3__LoginDevice(
    struct soap *soap,
    // request parameters:
    _icd1__LoginDevice*                 icd1__LoginDevice,
    // response parameters:
    _icd1__LoginDeviceResponse*         icd1__LoginDeviceResponse
  );
@endcode

C++ proxy class (defined in soapicdtcp3Soap12Proxy.h):
@code
  class icdtcp3Soap12Proxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapicdtcp3Soap12Service.h):
@code
  class icdtcp3Soap12Service;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap icd3 service method-style:	LoginDevice document
//gsoap icd3 service method-encoding:	LoginDevice literal
//gsoap icd3 service method-action:	LoginDevice http://insofter.pl/webservices/LoginDevice
//gsoap icd3 service method-output-action:	LoginDevice http://insofter.pl/webservices/icdtcp3Soap/LoginDeviceResponse
int __icd3__LoginDevice(
    _icd1__LoginDevice*                 icd1__LoginDevice,	///< Request parameter
    _icd1__LoginDeviceResponse*         icd1__LoginDeviceResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __icd3__SendData                                                         *
 *                                                                            *
\******************************************************************************/


/// Operation "__icd3__SendData" of service binding "icdtcp3Soap12"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://insofter.pl/webservices/SendData"

  - Addressing action: "http://insofter.pl/webservices/icdtcp3Soap/SendData"

  - Addressing response action: "http://insofter.pl/webservices/icdtcp3Soap/SendDataResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___icd3__SendData(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _icd1__SendData*                    icd1__SendData,
    // response parameters:
    _icd1__SendDataResponse*            icd1__SendDataResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __icd3__SendData(
    struct soap *soap,
    // request parameters:
    _icd1__SendData*                    icd1__SendData,
    // response parameters:
    _icd1__SendDataResponse*            icd1__SendDataResponse
  );
@endcode

C++ proxy class (defined in soapicdtcp3Soap12Proxy.h):
@code
  class icdtcp3Soap12Proxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapicdtcp3Soap12Service.h):
@code
  class icdtcp3Soap12Service;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap icd3 service method-style:	SendData document
//gsoap icd3 service method-encoding:	SendData literal
//gsoap icd3 service method-action:	SendData http://insofter.pl/webservices/SendData
//gsoap icd3 service method-output-action:	SendData http://insofter.pl/webservices/icdtcp3Soap/SendDataResponse
int __icd3__SendData(
    _icd1__SendData*                    icd1__SendData,	///< Request parameter
    _icd1__SendDataResponse*            icd1__SendDataResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __icd3__LogoutDevice                                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "__icd3__LogoutDevice" of service binding "icdtcp3Soap12"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action: "http://insofter.pl/webservices/LogoutDevice"

  - Addressing action: "http://insofter.pl/webservices/icdtcp3Soap/LogoutDevice"

  - Addressing response action: "http://insofter.pl/webservices/icdtcp3Soap/LogoutDeviceResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___icd3__LogoutDevice(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _icd1__LogoutDevice*                icd1__LogoutDevice,
    // response parameters:
    _icd1__LogoutDeviceResponse*        icd1__LogoutDeviceResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __icd3__LogoutDevice(
    struct soap *soap,
    // request parameters:
    _icd1__LogoutDevice*                icd1__LogoutDevice,
    // response parameters:
    _icd1__LogoutDeviceResponse*        icd1__LogoutDeviceResponse
  );
@endcode

C++ proxy class (defined in soapicdtcp3Soap12Proxy.h):
@code
  class icdtcp3Soap12Proxy;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapicdtcp3Soap12Service.h):
@code
  class icdtcp3Soap12Service;
@endcode
Important: use soapcpp2 option '-i' to generate greatly improved and easy-to-use service classes;

*/

//gsoap icd3 service method-style:	LogoutDevice document
//gsoap icd3 service method-encoding:	LogoutDevice literal
//gsoap icd3 service method-action:	LogoutDevice http://insofter.pl/webservices/LogoutDevice
//gsoap icd3 service method-output-action:	LogoutDevice http://insofter.pl/webservices/icdtcp3Soap/LogoutDeviceResponse
int __icd3__LogoutDevice(
    _icd1__LogoutDevice*                icd1__LogoutDevice,	///< Request parameter
    _icd1__LogoutDeviceResponse*        icd1__LogoutDeviceResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

XML content can be retrieved from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

XML content can be stored to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback


@section icd1 Top-level root elements of schema "http://insofter.pl/webservices"

  - <icd1:GetTime> @ref _icd1__GetTime
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__icd1__GetTime(struct soap*, _icd1__GetTime*);
    // Writer (returns SOAP_OK on success):
    soap_write__icd1__GetTime(struct soap*, _icd1__GetTime*);
    @endcode

  - <icd1:GetTimeResponse> @ref _icd1__GetTimeResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__icd1__GetTimeResponse(struct soap*, _icd1__GetTimeResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__icd1__GetTimeResponse(struct soap*, _icd1__GetTimeResponse*);
    @endcode

  - <icd1:LoginDevice> @ref _icd1__LoginDevice
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__icd1__LoginDevice(struct soap*, _icd1__LoginDevice*);
    // Writer (returns SOAP_OK on success):
    soap_write__icd1__LoginDevice(struct soap*, _icd1__LoginDevice*);
    @endcode

  - <icd1:LoginDeviceResponse> @ref _icd1__LoginDeviceResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__icd1__LoginDeviceResponse(struct soap*, _icd1__LoginDeviceResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__icd1__LoginDeviceResponse(struct soap*, _icd1__LoginDeviceResponse*);
    @endcode

  - <icd1:SendData> @ref _icd1__SendData
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__icd1__SendData(struct soap*, _icd1__SendData*);
    // Writer (returns SOAP_OK on success):
    soap_write__icd1__SendData(struct soap*, _icd1__SendData*);
    @endcode

  - <icd1:SendDataResponse> @ref _icd1__SendDataResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__icd1__SendDataResponse(struct soap*, _icd1__SendDataResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__icd1__SendDataResponse(struct soap*, _icd1__SendDataResponse*);
    @endcode

  - <icd1:LogoutDevice> @ref _icd1__LogoutDevice
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__icd1__LogoutDevice(struct soap*, _icd1__LogoutDevice*);
    // Writer (returns SOAP_OK on success):
    soap_write__icd1__LogoutDevice(struct soap*, _icd1__LogoutDevice*);
    @endcode

  - <icd1:LogoutDeviceResponse> @ref _icd1__LogoutDeviceResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__icd1__LogoutDeviceResponse(struct soap*, _icd1__LogoutDeviceResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__icd1__LogoutDeviceResponse(struct soap*, _icd1__LogoutDeviceResponse*);
    @endcode

*/

/* End of schem.h */
