// Automaticaly generated by the build system

const char *version = "v0.1-23-gab70881-dirty";
const char *build_date = "2012/08/30 13:26 CEST";
const char *copyright = "Copyright (c) 2011-2012 Tomasz Rozensztrauch";
