#!/bin/sh
#
# icd        Starts icd.
#
export ICD_TEMP_DIR=/tmp
export ICD_SHARE_DIR=/usr/share/icd
export ICD_DATA_DIR=/mnt/data

start()
{
  echo "Starting icd:"

  umask 000

  icd-create-config-db
  icd-create-flow-db
  icd-create-live-db

  chmod a+w "/tmp/live.db"

  icd-network start

  start-stop-daemon -S -p /tmp/icd-fc-daemon.pid -a icd-fc-daemon \
    -- --db="/tmp/live.db" --daemon --pidfile="/tmp/icd-fc-daemon.pid"

  ls /dev/itd*

  start-stop-daemon -S -p /tmp/icd-itd-daemon-itd0.pid -a icd-itd-daemon -- \
    --db="/tmp/live.db" --device="itd0" --daemon \
    --pidfile="/tmp/icd-itd-daemon-itd0.pid"
}	

stop()
{
  echo -n "Stopping sshd: "
  icd-network start
}

restart() 
{
 stop
 start
}	

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

