#!/bin/bash

icdtcp3-sql --db="${ICD_DB_DIR}/config.db" \
  "${ICD_SQL_SCRIPTS_DIR}/begin-transaction.sql" \
  "${ICD_SQL_SCRIPTS_DIR}/create-schema-config.sql" \
  "${ICD_SQL_SCRIPTS_DIR}/init-default-config.sql" \
  "${ICD_SQL_SCRIPTS_DIR}/commit-transaction.sql"

