#!/bin/bash

LOGDIR=/var/log

case "$1" in


start)
	if [ -e ${LOGDIR}/wpa_supplicant.log.0 ]
	then
		mv ${LOGDIR}/wpa_supplicant.log.0 ${LOGDIR}/wpa_supplicant.log.1
	fi
	if [ -e ${LOGDIR}/dhcpcd.wlan0.log.0 ]
	then
		mv ${LOGDIR}/dhcpcd.wlan0.log.0  ${LOGDIR}/dhcpcd.wlan0.log.1
	fi
	wpa_supplicant -Dwext -iwlan0 -d -c /var/www/wpa_supplicant.conf > ${LOGDIR}/wpa_supplicant.log.0 & 
	echo OK
	#w petli az uzyska bo sie wylacza 
	if ! [ -e /run/dhcpcd-wlan0.pid ]
	then
	    while [ 1=1 ]
    	do
			dhcpcd wlan0 >> ${LOGDIR}/dhcpcd.wlan0.log.0 2>&1 && break
			echo "WARNING -- reset dhcpcd" >> ${LOGDIR}/dhcpcd.wlan0.log.0
			if ! [ `pidof /usr/sbin/wpa_supplicant`0 -gt 0 ] 
			then
				echo "WARNING -- wpa_supplicant killed" >> ${LOGDIR}/dhcpcd.wlan0.log.0
				break
			fi	      
			sleep 2 
		done
	fi	
	;;


stop)
	killall wpa_supplicant && echo OK
	;;


reset)
	$0 stop
	sleep 1
	$0 start
	;;


stat)
	wpa_cli -i wlan0 status 
	;;

lstn) 
	wpa_cli -i wlan0 list_networks | tail -n +2
	;;	

scan)
	wpa_cli -i wlan0 scan 
	;;

rscn)
	wpa_cli -i wlan0 scan_results | tail -n +2
	;;

addn)
	#wykrywanie typu
	num=`wpa_cli -i wlan0 add_network`
	if [ "$3" = "" ]
	then
		wpa_cli -i wlan0 set_network $num key_mgmt NONE

	else
		wpa_cli -i wlan0 set_network $num auth_alg OPEN
		wpa_cli -i wlan0 set_network $num key_mgmt WPA-PSK
		wpa_cli -i wlan0 set_network $num psk '"'"${3}"'"'
		wpa_cli -i wlan0 set_network $num mode 0
	fi

	wpa_cli -i wlan0 set_network $num ssid '"'"${2}"'"'
	#wpa_cli -i wlan0 select_network $num
	wpa_cli -i wlan0 enable_network $num
	wpa_cli -i wlan0 reassociate
	wpa_cli -i wlan0 save_config
	;;

deln)
    wpa_cli -i wlan0 remove_network "${2}"
	wpa_cli -i wlan0 save_config
#	sleep 1
#	killall wpa_supplicant && echo OK
#	sleep 3
#	wpa_supplicant -Dwext -iwlan0 -d -c /var/www/wpa_supplicant.conf > ${LOGDIR}/wpa_supplicant.log & 
	echo OK
	#TODO: 
;;

enab)
	wpa_cli -i wlan0 enable_network "${2}"
	wpa_cli -i wlan0 save_config
	echo "enab ${2}" >> ${LOGDIR}/wpa.sh.log
	#enable all
	;;
	 
disb)
	wpa_cli -i wlan0 disable_network "${2}"
	wpa_cli -i wlan0 save_config
	echo "disb ${2}" >> ${LOGDIR}/wpa.sh.log
	;;
	
cfg-to-db)
	i=0
	n=`icd-config -d /var/www/icdtcp3/live.db sget wpa network-count`
	while [ $i -lt $n ]
	do
		icd-config -d /var/www/icdtcp3/live.db rm wpa network-${i}
		i=$[ $i+1 ]
	done

	if [ `pidof /usr/sbin/wpa_supplicant`0 -gt 0 ] 
	then
		wpa_cli -i wlan0 save_config
	fi

	i=0
	for x in `cat /var/www/wpa_supplicant.conf | tail -n +5 \
		| sed '/^$/d' \
		| sed -e 's/ /~/g' \
		| sed -e 's/^[ \t]*//' \
		| tr '\n' ';'\
		| sed -e "s/network=//g; s/\"/\'/g; s/\r/ /g" \
		| sed -e 's/{;//g; s/;};/\n/g'`
	do
		icd-config -d /var/www/icdtcp3/live.db set wpa network-${i} "`echo $x | sed -e 's/~/ /g'`" 
		i=$[ $i+1 ]
	done

	icd-config -d /var/www/icdtcp3/live.db set wpa network-count "$i"
	
	;;


cfg-from-db)
	st=0
	if [ `pidof /usr/sbin/wpa_supplicant`0 -gt 0 ] 
	then
		st=1
		$0 stop
		sleep 1
	fi

	if [ -e /var/www/wpa_supplicant.conf ]
	then
		mv /var/www/wpa_supplicant.conf /srv/www/wpa_supplicant.conf.old
	fi

	cat << WPA_HEAD > /var/www/wpa_supplicant.conf
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=wheel
update_config=1

WPA_HEAD

	i=0
	n=`icd-config -d /var/www/icdtcp3/live.db sget wpa network-count`

	while [ $i -lt $n ]
	do
		echo `icd-config -d /var/www/icdtcp3/live.db sget wpa network-${i}` \
			| sed -e 's/;/;\t/g' \
			| sed -e 's/^/network={;\t/g; s/$/;};/g' \
			| sed -e "s/;/\n/g; s/'/\"/g"  >> /var/www/wpa_supplicant.conf
		i=$[ $i+1 ]
	done

	if [ $st -eq 1 ]
	then
		sleep 1
		$0 start
	fi
	;;


esac






