#!/bin/sh

source "/etc/profile.d/icd.sh"

PROGRAM_NAME=`basename "$0"`

check_error()
{
  if [ $? != 0 ] ; then
    echo "Error! ${PROGRAM_NAME} halted."
    exit 1
  fi
}

icd-sql --db="${ICD_DATA_DIR}/config.db" \
  --extern-db="${ICD_TEMP_DIR}/live.db" \
  "${ICD_SHARE_DIR}/sync-config.sql"
check_error

