#!/bin/sh

PROGRAM_NAME=`basename "$0"`

check_error()
{
  if [ $? != 0 ] ; then
    echo "Error! ${PROGRAM_NAME} halted."
    exit 1
  fi
}

if [ ! -f "${ICD_DATA_DB}" ]; then
  icd-sql --db="${ICD_DATA_DB}" \
    "${ICD_SHARE_DIR}/create-schema-flow.sql"
  check_error
  chown icdtcp3:icdtcp3 $ICD_DATA_DB
  check_error
fi

