#!/bin/sh

source "/etc/profile.d/icd.sh"

PROGRAM_NAME=`basename "$0"`

check_error()
{
  if [ $? != 0 ] ; then
    echo "Error! ${PROGRAM_NAME} halted."
    exit 1
  fi
}

if [ ! -f "${ICD_CONFIG_DB}" ]; then
  icd-sql --db="${ICD_CONFIG_DB}" \
    "${ICD_SHARE_DIR}/create-schema-config.sql" \
    "${ICD_SHARE_DIR}/init-default-config.sql"
  check_error
  chown icdtcp3:icdtcp3 $ICD_CONFIG_DB
  check_error
  chown icdtcp3:icdtcp3 /home/data/

else
  icd-sql --db="${ICD_CONFIG_DB}" \
    "${ICD_SHARE_DIR}/clear-old-current.sql"
  check_error
fi

