#!/bin/sh

if [ "`icd-config --db=$ICD_CONFIG_DB sget tcpip dhcp`" = "no" ] && [ "`icd-config --db=$ICD_CONFIG_DB sget tcpip dnsmasq`" = "yes" ]
then 
  date

  ip=`icd-config --db="${ICD_CONFIG_DB}" sget tcpip ip`
  mask=`icd-config --db="${ICD_CONFIG_DB}" sget tcpip mask`

  net=`echo ${ip}"."${mask} | awk -F '.' '{ print and($1 ,$5) "." and($2 ,$6) "." and($3 ,$7) "." and($4, $8 ) }'`
  ipend=`echo ${ip} | awk -F '.' '{ print $4 }'`
  ipbeg=`echo ${ip} | awk -F '.' '{ print $1 "." $2 "." $3 }'`

  echo "Host IP:     $ip"
  echo "Subnet IP:   $net"
  echo "Subnet mask: $mask"

  echo 1 > /proc/sys/net/ipv4/ip_forward
  echo "Activate ip forwarding."
  echo "    echo 1 > /proc/sys/net/ipv4/ip_forward"


  iptables -t nat -A POSTROUTING -s $net/$mask -d 0.0.0.0/0 -j MASQUERADE
  echo "Add iptables rules:"
  echo "    iptables -t nat -A POSTROUTING -s $net/$mask -d 0.0.0.0/0 -j MASQUERADE)"

  echo "interface=eth0" > /tmp/dnsmasq.conf
  echo "cache-size=0" >> /tmp/dnsmasq.conf

  if [ "$ipend" -ge 100 ]
  then
    echo "dhcp-range=${ipbeg}.20,${ipbeg}.99,${mask},1h" >> /tmp/dnsmasq.conf
  else
    echo "dhcp-range=${ipbeg}.100,${ipbeg}.199,${mask},1h" >> /tmp/dnsmasq.conf
  fi

  echo "Create dnsmasq config: (/tmp/dnsmasq.conf)"
  cat /tmp/dnsmasq.conf | awk '{ print "    " $0 }'

  dnsmasq -C /tmp/dnsmasq.conf
  echo "Run dnsmasq:"
  echo "    dnsmasq -C /tmp/dnsmasq.conf"

else
  echo "Masquerade is turned off."
fi

