#!/bin/sh

case "$1" in

  eth)
    case "$2" in
      ip)
        ifconfig eth0 | sed -n 's/^[^i]*inet addr:\([0-9.][0-9.]*\).*$/\1/p'
        ;;
      mask)
        ifconfig eth0 | sed -n 's/^[^M]*Mask:\([0-9.][0-9.]*\).*$/\1/p'
        ;;
      gate)
        route | sed -n 's/^default[[:space:]]*\([0-9.][0-9.]*\).*$/\1/p' | head -1
        ;;
      dns1)
        cat /etc/resolv.conf | awk '/nameserver/ {print $2}' | sed -n 1p
        ;;
      dns2)
        cat /etc/resolv.conf | awk '/nameserver/ {print $2}' | sed -n 2p
        ;;
      mac)
        ifconfig eth0 | sed -n 's/^[^H]*HWaddr[[:space:]]*\([[:xdigit:]:][[:xdigit:]:]*\).*$/\1/p'
        ;;
    esac
    ;;

  wifi)
    case "$2" in
      ip)
        wpa_cli -i wlan0 status 2>/dev/null | awk -F '=' ''/'ip_address'/' {print $2}'
        ;;
      ssid)
        wpa_cli -i wlan0 status 2>/dev/null | grep -v bssid | awk -F '=' ''/'ssid'/' {print $2}'
        ;;
      ip-ssid)
        echo -n `wpa_cli -i wlan0 status 2>/dev/null | awk -F '=' ''/'ip_address'/' {print $2}'` 
        echo -n " -- "
        echo `wpa_cli -i wlan0 status 2>/dev/null | grep -v bssid | awk -F '=' ''/'ssid'/' {print $2}'`
        ;;
    esac
    ;;
esac
