#!/bin/sh

PROGRAM_NAME=`basename "$0"`

check_error()
{
  if [ $? != 0 ] ; then
    echo "Error! ${PROGRAM_NAME} halted."
    exit 1
  fi
}

rm -f "${ICD_LIVE_DB}" 

icd-sql --db="${ICD_LIVE_DB}" \
  "${ICD_SHARE_DIR}/create-schema-flow.sql" \
check_error

chmod a+w "${ICD_LIVE_DB}"

