#!/bin/sh

case "$1" in

  eth)
    case "$2" in
      ip)
        ifconfig eth0 | sed -n 's/^[^i]*inet addr:\([0-9.][0-9.]*\).*$/\1/p'
        ;;
      mask)
        ifconfig eth0 | sed -n 's/^[^M]*Mask:\([0-9.][0-9.]*\).*$/\1/p'
        ;;
      gate)
        route | sed -n 's/^default[[:space:]]*\([0-9.][0-9.]*\).*$/\1/p' | head -1
        ;;
      dns1)
        cat /etc/resolv.conf | awk '/nameserver/ {print $2}' | sed -n 1p
        ;;
      dns2)
        cat /etc/resolv.conf | awk '/nameserver/ {print $2}' | sed -n 2p
        ;;
      mac)
        ifconfig eth0 | sed -n 's/^[^H]*HWaddr[[:space:]]*\([[:xdigit:]:][[:xdigit:]:]*\).*$/\1/p'
        ;;
    esac
    ;;

  wifi)
    case "$2" in
      ip)
        wpa_cli -i wlan0 status 2>/dev/null | awk -F '=' ''/'ip_address'/' {print $2}'
        ;;
      ssid)
        wpa_cli -i wlan0 status 2>/dev/null | grep -v bssid | awk -F '=' ''/'ssid'/' {print $2}'
        ;;
      ip-ssid)
        echo -n `wpa_cli -i wlan0 status 2>/dev/null | awk -F '=' ''/'ip_address'/' {print $2}'` 
        echo -n " -- "
        echo `wpa_cli -i wlan0 status 2>/dev/null | grep -v bssid | awk -F '=' ''/'ssid'/' {print $2}'`
        ;;
    esac
    ;;
  gsm)
    case "$2" in
      pin_enabled)
        if [ "`wvdial $2 -C $ICD_SHARE_DIR/gsm/common_wvdial.conf 2>&1 | grep '^+CLCK:' | awk '{print $2}'`" = "1" ]; then
          echo "yes"
        else
          echo "no"
        fi
        ;;
      pin_status)
        wvdial $2 -C $ICD_SHARE_DIR/gsm/common_wvdial.conf 2>&1 | grep "^+CPIN:" | awk '{print $2}'
        ;;
      logged)
        if [ "`wvdial $2 -C $ICD_SHARE_DIR/gsm/common_wvdial.conf 2>&1 | grep '^+CREG:' | awk '{print $2}'`" = "0,1" ]; then
          echo "yes"
        else
          echo "no"
        fi
    esac
    ;;
esac
