// Automaticaly generated by the build system

const char *version = "v0.1-3-gb44ba58-dirty";
const char *build_date = "2012/08/09 11:05 CEST";
const char *copyright = "Copyright (c) 2011-2012 Tomasz Rozensztrauch";
