// Automaticaly generated by the build system

const char *version = "v0.1-2-gd96ea7c-dirty";
const char *build_date = "2012/08/09 09:43 CEST";
const char *copyright = "Copyright (c) 2011-2012 Tomasz Rozensztrauch";
