// Automaticaly generated by the build system

const char *version = "v0.1-27-g3b8a0ee-dirty";
const char *build_date = "2012/08/31 13:30 CEST";
const char *copyright = "Copyright (c) 2011-2012 Tomasz Rozensztrauch";
